from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.create_mapping_rule_response_201 import CreateMappingRuleResponse201
from ...models.mapping_rule_create_request import MappingRuleCreateRequest
from ...models.problem_detail import ProblemDetail
from ...types import UNSET, Response, Unset
def _get_kwargs(body: MappingRuleCreateRequest | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> CreateMappingRuleResponse201 | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[CreateMappingRuleResponse201 | ProblemDetail]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: MappingRuleCreateRequest | Unset = UNSET) -> Response[CreateMappingRuleResponse201 | ProblemDetail]: ...
def sync(client: AuthenticatedClient | Client, body: MappingRuleCreateRequest | Unset = UNSET, **kwargs: Any) -> CreateMappingRuleResponse201: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: MappingRuleCreateRequest | Unset = UNSET) -> Response[CreateMappingRuleResponse201 | ProblemDetail]: ...
async def asyncio(client: AuthenticatedClient | Client, body: MappingRuleCreateRequest | Unset = UNSET, **kwargs: Any) -> CreateMappingRuleResponse201: ...
