from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.mapping_rule_result import MappingRuleResult
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(mapping_rule_id: str) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> MappingRuleResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[MappingRuleResult | ProblemDetail]: ...
def sync_detailed(mapping_rule_id: str, client: AuthenticatedClient | Client) -> Response[MappingRuleResult | ProblemDetail]: ...
def sync(mapping_rule_id: str, client: AuthenticatedClient | Client, **kwargs: Any) -> MappingRuleResult: ...
async def asyncio_detailed(mapping_rule_id: str, client: AuthenticatedClient | Client) -> Response[MappingRuleResult | ProblemDetail]: ...
async def asyncio(mapping_rule_id: str, client: AuthenticatedClient | Client, **kwargs: Any) -> MappingRuleResult: ...
