from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.mapping_rule_search_query_request import MappingRuleSearchQueryRequest
from ...models.problem_detail import ProblemDetail
from ...models.search_mapping_rule_response_200 import SearchMappingRuleResponse200
from ...types import UNSET, Response, Unset
def _get_kwargs(body: MappingRuleSearchQueryRequest | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ProblemDetail | SearchMappingRuleResponse200 | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ProblemDetail | SearchMappingRuleResponse200]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: MappingRuleSearchQueryRequest | Unset = UNSET) -> Response[ProblemDetail | SearchMappingRuleResponse200]: ...
def sync(client: AuthenticatedClient | Client, body: MappingRuleSearchQueryRequest | Unset = UNSET, **kwargs: Any) -> SearchMappingRuleResponse200: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: MappingRuleSearchQueryRequest | Unset = UNSET) -> Response[ProblemDetail | SearchMappingRuleResponse200]: ...
async def asyncio(client: AuthenticatedClient | Client, body: MappingRuleSearchQueryRequest | Unset = UNSET, **kwargs: Any) -> SearchMappingRuleResponse200: ...
