from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.mapping_rule_update_request import MappingRuleUpdateRequest
from ...models.problem_detail import ProblemDetail
from ...models.update_mapping_rule_response_200 import UpdateMappingRuleResponse200
from ...types import UNSET, Response, Unset
def _get_kwargs(mapping_rule_id: str, body: MappingRuleUpdateRequest | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ProblemDetail | UpdateMappingRuleResponse200 | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ProblemDetail | UpdateMappingRuleResponse200]: ...
def sync_detailed(mapping_rule_id: str, client: AuthenticatedClient | Client, body: MappingRuleUpdateRequest | Unset = UNSET) -> Response[ProblemDetail | UpdateMappingRuleResponse200]: ...
def sync(mapping_rule_id: str, client: AuthenticatedClient | Client, body: MappingRuleUpdateRequest | Unset = UNSET, **kwargs: Any) -> UpdateMappingRuleResponse200: ...
async def asyncio_detailed(mapping_rule_id: str, client: AuthenticatedClient | Client, body: MappingRuleUpdateRequest | Unset = UNSET) -> Response[ProblemDetail | UpdateMappingRuleResponse200]: ...
async def asyncio(mapping_rule_id: str, client: AuthenticatedClient | Client, body: MappingRuleUpdateRequest | Unset = UNSET, **kwargs: Any) -> UpdateMappingRuleResponse200: ...
