from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.create_global_task_listener_request import CreateGlobalTaskListenerRequest
from ...models.global_task_listener_result import GlobalTaskListenerResult
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(body: CreateGlobalTaskListenerRequest) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> GlobalTaskListenerResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[GlobalTaskListenerResult | ProblemDetail]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: CreateGlobalTaskListenerRequest) -> Response[GlobalTaskListenerResult | ProblemDetail]: ...
def sync(client: AuthenticatedClient | Client, body: CreateGlobalTaskListenerRequest, **kwargs: Any) -> GlobalTaskListenerResult: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: CreateGlobalTaskListenerRequest) -> Response[GlobalTaskListenerResult | ProblemDetail]: ...
async def asyncio(client: AuthenticatedClient | Client, body: CreateGlobalTaskListenerRequest, **kwargs: Any) -> GlobalTaskListenerResult: ...
