from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.global_task_listener_result import GlobalTaskListenerResult
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(id: str) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> GlobalTaskListenerResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[GlobalTaskListenerResult | ProblemDetail]: ...
def sync_detailed(id: str, client: AuthenticatedClient | Client) -> Response[GlobalTaskListenerResult | ProblemDetail]: ...
def sync(id: str, client: AuthenticatedClient | Client, **kwargs: Any) -> GlobalTaskListenerResult: ...
async def asyncio_detailed(id: str, client: AuthenticatedClient | Client) -> Response[GlobalTaskListenerResult | ProblemDetail]: ...
async def asyncio(id: str, client: AuthenticatedClient | Client, **kwargs: Any) -> GlobalTaskListenerResult: ...
