from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.global_task_listener_search_query_request import GlobalTaskListenerSearchQueryRequest
from ...models.global_task_listener_search_query_result import GlobalTaskListenerSearchQueryResult
from ...models.problem_detail import ProblemDetail
from ...types import UNSET, Response, Unset
def _get_kwargs(body: GlobalTaskListenerSearchQueryRequest | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> GlobalTaskListenerSearchQueryResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[GlobalTaskListenerSearchQueryResult | ProblemDetail]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: GlobalTaskListenerSearchQueryRequest | Unset = UNSET) -> Response[GlobalTaskListenerSearchQueryResult | ProblemDetail]: ...
def sync(client: AuthenticatedClient | Client, body: GlobalTaskListenerSearchQueryRequest | Unset = UNSET, **kwargs: Any) -> GlobalTaskListenerSearchQueryResult: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: GlobalTaskListenerSearchQueryRequest | Unset = UNSET) -> Response[GlobalTaskListenerSearchQueryResult | ProblemDetail]: ...
async def asyncio(client: AuthenticatedClient | Client, body: GlobalTaskListenerSearchQueryRequest | Unset = UNSET, **kwargs: Any) -> GlobalTaskListenerSearchQueryResult: ...
