from __future__ import annotations

from typing import Any
class ApiError(Exception):
    def __init__(self, *, status_code: int, content: bytes, parsed: Any | None = None, operation_id: str | None = None) -> None: ...
    def _build_message(self) -> str: ...
class UnexpectedStatus(ApiError):
    def __init__(self, status_code: int, content: bytes, *, operation_id: str | None = None) -> None: ...
class BadRequestError(ApiError):
    ...
class UnauthorizedError(ApiError):
    ...
class PaymentRequiredError(ApiError):
    ...
class ForbiddenError(ApiError):
    ...
class NotFoundError(ApiError):
    ...
class MethodNotAllowedError(ApiError):
    ...
class RequestTimeoutError(ApiError):
    ...
class ConflictError(ApiError):
    ...
class GoneError(ApiError):
    ...
class PreconditionFailedError(ApiError):
    ...
class PayloadTooLargeError(ApiError):
    ...
class UnsupportedMediaTypeError(ApiError):
    ...
class UnprocessableEntityError(ApiError):
    ...
class TooManyRequestsError(ApiError):
    ...
class InternalServerErrorError(ApiError):
    ...
class NotImplementedError_(ApiError):
    ...
class BadGatewayError(ApiError):
    ...
class ServiceUnavailableError(ApiError):
    ...
class GatewayTimeoutError(ApiError):
    ...
__all__ = ['ApiError', 'BadGatewayError', 'BadRequestError', 'ConflictError', 'ForbiddenError', 'GatewayTimeoutError', 'GoneError', 'InternalServerErrorError', 'MethodNotAllowedError', 'NotFoundError', 'NotImplementedError_', 'PayloadTooLargeError', 'PaymentRequiredError', 'PreconditionFailedError', 'RequestTimeoutError', 'ServiceUnavailableError', 'TooManyRequestsError', 'UnauthorizedError', 'UnexpectedStatus', 'UnprocessableEntityError', 'UnsupportedMediaTypeError']
