from __future__ import annotations

from typing import Any, Tuple, Union
class AuditLogEntityKey(str):
    def __new__(cls, value: Any) -> "AuditLogEntityKey": ...
def lift_audit_log_entity_key(value: Any) -> AuditLogEntityKey: ...
def try_lift_audit_log_entity_key(value: Any) -> Tuple[bool, AuditLogEntityKey | Exception]: ...
class AuditLogKey(str):
    def __new__(cls, value: Any) -> "AuditLogKey": ...
def lift_audit_log_key(value: Any) -> AuditLogKey: ...
def try_lift_audit_log_key(value: Any) -> Tuple[bool, AuditLogKey | Exception]: ...
class AuthorizationKey(str):
    def __new__(cls, value: Any) -> "AuthorizationKey": ...
def lift_authorization_key(value: Any) -> AuthorizationKey: ...
def try_lift_authorization_key(value: Any) -> Tuple[bool, AuthorizationKey | Exception]: ...
class BatchOperationKey(str):
    def __new__(cls, value: Any) -> "BatchOperationKey": ...
def lift_batch_operation_key(value: Any) -> BatchOperationKey: ...
def try_lift_batch_operation_key(value: Any) -> Tuple[bool, BatchOperationKey | Exception]: ...
class BusinessId(str):
    def __new__(cls, value: Any) -> "BusinessId": ...
def lift_business_id(value: Any) -> BusinessId: ...
def try_lift_business_id(value: Any) -> Tuple[bool, BusinessId | Exception]: ...
class ConditionalEvaluationKey(str):
    def __new__(cls, value: Any) -> "ConditionalEvaluationKey": ...
def lift_conditional_evaluation_key(value: Any) -> ConditionalEvaluationKey: ...
def try_lift_conditional_evaluation_key(value: Any) -> Tuple[bool, ConditionalEvaluationKey | Exception]: ...
class DecisionDefinitionId(str):
    def __new__(cls, value: Any) -> "DecisionDefinitionId": ...
def lift_decision_definition_id(value: Any) -> DecisionDefinitionId: ...
def try_lift_decision_definition_id(value: Any) -> Tuple[bool, DecisionDefinitionId | Exception]: ...
class DecisionDefinitionKey(str):
    def __new__(cls, value: Any) -> "DecisionDefinitionKey": ...
def lift_decision_definition_key(value: Any) -> DecisionDefinitionKey: ...
def try_lift_decision_definition_key(value: Any) -> Tuple[bool, DecisionDefinitionKey | Exception]: ...
class DecisionEvaluationInstanceKey(str):
    def __new__(cls, value: Any) -> "DecisionEvaluationInstanceKey": ...
def lift_decision_evaluation_instance_key(value: Any) -> DecisionEvaluationInstanceKey: ...
def try_lift_decision_evaluation_instance_key(value: Any) -> Tuple[bool, DecisionEvaluationInstanceKey | Exception]: ...
class DecisionEvaluationKey(str):
    def __new__(cls, value: Any) -> "DecisionEvaluationKey": ...
def lift_decision_evaluation_key(value: Any) -> DecisionEvaluationKey: ...
def try_lift_decision_evaluation_key(value: Any) -> Tuple[bool, DecisionEvaluationKey | Exception]: ...
class DecisionInstanceKey(str):
    def __new__(cls, value: Any) -> "DecisionInstanceKey": ...
def lift_decision_instance_key(value: Any) -> DecisionInstanceKey: ...
def try_lift_decision_instance_key(value: Any) -> Tuple[bool, DecisionInstanceKey | Exception]: ...
class DecisionRequirementsKey(str):
    def __new__(cls, value: Any) -> "DecisionRequirementsKey": ...
def lift_decision_requirements_key(value: Any) -> DecisionRequirementsKey: ...
def try_lift_decision_requirements_key(value: Any) -> Tuple[bool, DecisionRequirementsKey | Exception]: ...
class DeploymentKey(str):
    def __new__(cls, value: Any) -> "DeploymentKey": ...
def lift_deployment_key(value: Any) -> DeploymentKey: ...
def try_lift_deployment_key(value: Any) -> Tuple[bool, DeploymentKey | Exception]: ...
class DocumentId(str):
    def __new__(cls, value: Any) -> "DocumentId": ...
def lift_document_id(value: Any) -> DocumentId: ...
def try_lift_document_id(value: Any) -> Tuple[bool, DocumentId | Exception]: ...
class ElementId(str):
    def __new__(cls, value: Any) -> "ElementId": ...
def lift_element_id(value: Any) -> ElementId: ...
def try_lift_element_id(value: Any) -> Tuple[bool, ElementId | Exception]: ...
class ElementInstanceKey(str):
    def __new__(cls, value: Any) -> "ElementInstanceKey": ...
def lift_element_instance_key(value: Any) -> ElementInstanceKey: ...
def try_lift_element_instance_key(value: Any) -> Tuple[bool, ElementInstanceKey | Exception]: ...
class EndCursor(str):
    def __new__(cls, value: Any) -> "EndCursor": ...
def lift_end_cursor(value: Any) -> EndCursor: ...
def try_lift_end_cursor(value: Any) -> Tuple[bool, EndCursor | Exception]: ...
class FormId(str):
    def __new__(cls, value: Any) -> "FormId": ...
def lift_form_id(value: Any) -> FormId: ...
def try_lift_form_id(value: Any) -> Tuple[bool, FormId | Exception]: ...
class FormKey(str):
    def __new__(cls, value: Any) -> "FormKey": ...
def lift_form_key(value: Any) -> FormKey: ...
def try_lift_form_key(value: Any) -> Tuple[bool, FormKey | Exception]: ...
class GlobalListenerId(str):
    def __new__(cls, value: Any) -> "GlobalListenerId": ...
def lift_global_listener_id(value: Any) -> GlobalListenerId: ...
def try_lift_global_listener_id(value: Any) -> Tuple[bool, GlobalListenerId | Exception]: ...
class IncidentKey(str):
    def __new__(cls, value: Any) -> "IncidentKey": ...
def lift_incident_key(value: Any) -> IncidentKey: ...
def try_lift_incident_key(value: Any) -> Tuple[bool, IncidentKey | Exception]: ...
class JobKey(str):
    def __new__(cls, value: Any) -> "JobKey": ...
def lift_job_key(value: Any) -> JobKey: ...
def try_lift_job_key(value: Any) -> Tuple[bool, JobKey | Exception]: ...
class MessageKey(str):
    def __new__(cls, value: Any) -> "MessageKey": ...
def lift_message_key(value: Any) -> MessageKey: ...
def try_lift_message_key(value: Any) -> Tuple[bool, MessageKey | Exception]: ...
class MessageSubscriptionKey(str):
    def __new__(cls, value: Any) -> "MessageSubscriptionKey": ...
def lift_message_subscription_key(value: Any) -> MessageSubscriptionKey: ...
def try_lift_message_subscription_key(value: Any) -> Tuple[bool, MessageSubscriptionKey | Exception]: ...
class ProcessDefinitionId(str):
    def __new__(cls, value: Any) -> "ProcessDefinitionId": ...
def lift_process_definition_id(value: Any) -> ProcessDefinitionId: ...
def try_lift_process_definition_id(value: Any) -> Tuple[bool, ProcessDefinitionId | Exception]: ...
class ProcessDefinitionKey(str):
    def __new__(cls, value: Any) -> "ProcessDefinitionKey": ...
def lift_process_definition_key(value: Any) -> ProcessDefinitionKey: ...
def try_lift_process_definition_key(value: Any) -> Tuple[bool, ProcessDefinitionKey | Exception]: ...
class ProcessInstanceKey(str):
    def __new__(cls, value: Any) -> "ProcessInstanceKey": ...
def lift_process_instance_key(value: Any) -> ProcessInstanceKey: ...
def try_lift_process_instance_key(value: Any) -> Tuple[bool, ProcessInstanceKey | Exception]: ...
class SignalKey(str):
    def __new__(cls, value: Any) -> "SignalKey": ...
def lift_signal_key(value: Any) -> SignalKey: ...
def try_lift_signal_key(value: Any) -> Tuple[bool, SignalKey | Exception]: ...
class StartCursor(str):
    def __new__(cls, value: Any) -> "StartCursor": ...
def lift_start_cursor(value: Any) -> StartCursor: ...
def try_lift_start_cursor(value: Any) -> Tuple[bool, StartCursor | Exception]: ...
class Tag(str):
    def __new__(cls, value: Any) -> "Tag": ...
def lift_tag(value: Any) -> Tag: ...
def try_lift_tag(value: Any) -> Tuple[bool, Tag | Exception]: ...
class TenantId(str):
    def __new__(cls, value: Any) -> "TenantId": ...
def lift_tenant_id(value: Any) -> TenantId: ...
def try_lift_tenant_id(value: Any) -> Tuple[bool, TenantId | Exception]: ...
class UserTaskKey(str):
    def __new__(cls, value: Any) -> "UserTaskKey": ...
def lift_user_task_key(value: Any) -> UserTaskKey: ...
def try_lift_user_task_key(value: Any) -> Tuple[bool, UserTaskKey | Exception]: ...
class Username(str):
    def __new__(cls, value: Any) -> "Username": ...
def lift_username(value: Any) -> Username: ...
def try_lift_username(value: Any) -> Tuple[bool, Username | Exception]: ...
class VariableKey(str):
    def __new__(cls, value: Any) -> "VariableKey": ...
def lift_variable_key(value: Any) -> VariableKey: ...
def try_lift_variable_key(value: Any) -> Tuple[bool, VariableKey | Exception]: ...
ResourceKey = Union[ProcessDefinitionKey, DecisionRequirementsKey, FormKey, DecisionDefinitionKey]
def lift_resource_key(value: Any) -> ResourceKey: ...
def try_lift_resource_key(value: Any) -> Tuple[bool, ResourceKey | Exception]: ...
ScopeKey = Union[ProcessInstanceKey, ElementInstanceKey]
def lift_scope_key(value: Any) -> ScopeKey: ...
def try_lift_scope_key(value: Any) -> Tuple[bool, ScopeKey | Exception]: ...
__all__ = ['AuditLogEntityKey', 'AuditLogKey', 'AuthorizationKey', 'BatchOperationKey', 'BusinessId', 'ConditionalEvaluationKey', 'DecisionDefinitionId', 'DecisionDefinitionKey', 'DecisionEvaluationInstanceKey', 'DecisionEvaluationKey', 'DecisionInstanceKey', 'DecisionRequirementsKey', 'DeploymentKey', 'DocumentId', 'ElementId', 'ElementInstanceKey', 'EndCursor', 'FormId', 'FormKey', 'GlobalListenerId', 'IncidentKey', 'JobKey', 'MessageKey', 'MessageSubscriptionKey', 'ProcessDefinitionId', 'ProcessDefinitionKey', 'ProcessInstanceKey', 'ResourceKey', 'ScopeKey', 'SignalKey', 'StartCursor', 'Tag', 'TenantId', 'UserTaskKey', 'Username', 'VariableKey', 'lift_audit_log_entity_key', 'lift_audit_log_key', 'lift_authorization_key', 'lift_batch_operation_key', 'lift_business_id', 'lift_conditional_evaluation_key', 'lift_decision_definition_id', 'lift_decision_definition_key', 'lift_decision_evaluation_instance_key', 'lift_decision_evaluation_key', 'lift_decision_instance_key', 'lift_decision_requirements_key', 'lift_deployment_key', 'lift_document_id', 'lift_element_id', 'lift_element_instance_key', 'lift_end_cursor', 'lift_form_id', 'lift_form_key', 'lift_global_listener_id', 'lift_incident_key', 'lift_job_key', 'lift_message_key', 'lift_message_subscription_key', 'lift_process_definition_id', 'lift_process_definition_key', 'lift_process_instance_key', 'lift_resource_key', 'lift_scope_key', 'lift_signal_key', 'lift_start_cursor', 'lift_tag', 'lift_tenant_id', 'lift_user_task_key', 'lift_username', 'lift_variable_key', 'try_lift_audit_log_entity_key', 'try_lift_audit_log_key', 'try_lift_authorization_key', 'try_lift_batch_operation_key', 'try_lift_business_id', 'try_lift_conditional_evaluation_key', 'try_lift_decision_definition_id', 'try_lift_decision_definition_key', 'try_lift_decision_evaluation_instance_key', 'try_lift_decision_evaluation_key', 'try_lift_decision_instance_key', 'try_lift_decision_requirements_key', 'try_lift_deployment_key', 'try_lift_document_id', 'try_lift_element_id', 'try_lift_element_instance_key', 'try_lift_end_cursor', 'try_lift_form_id', 'try_lift_form_key', 'try_lift_global_listener_id', 'try_lift_incident_key', 'try_lift_job_key', 'try_lift_message_key', 'try_lift_message_subscription_key', 'try_lift_process_definition_id', 'try_lift_process_definition_key', 'try_lift_process_instance_key', 'try_lift_resource_key', 'try_lift_scope_key', 'try_lift_signal_key', 'try_lift_start_cursor', 'try_lift_tag', 'try_lift_tenant_id', 'try_lift_user_task_key', 'try_lift_username', 'try_lift_variable_key']
