from __future__ import annotations

from typing import NewType, Any, Tuple
AuditLogEntityKey = NewType('AuditLogEntityKey', str)
def lift_audit_log_entity_key(value: Any) -> AuditLogEntityKey: ...
def try_lift_audit_log_entity_key(value: Any) -> Tuple[bool, AuditLogEntityKey | Exception]: ...
AuditLogKey = NewType('AuditLogKey', str)
def lift_audit_log_key(value: Any) -> AuditLogKey: ...
def try_lift_audit_log_key(value: Any) -> Tuple[bool, AuditLogKey | Exception]: ...
AuthorizationKey = NewType('AuthorizationKey', str)
def lift_authorization_key(value: Any) -> AuthorizationKey: ...
def try_lift_authorization_key(value: Any) -> Tuple[bool, AuthorizationKey | Exception]: ...
BatchOperationKey = NewType('BatchOperationKey', str)
def lift_batch_operation_key(value: Any) -> BatchOperationKey: ...
def try_lift_batch_operation_key(value: Any) -> Tuple[bool, BatchOperationKey | Exception]: ...
ConditionalEvaluationKey = NewType('ConditionalEvaluationKey', str)
def lift_conditional_evaluation_key(value: Any) -> ConditionalEvaluationKey: ...
def try_lift_conditional_evaluation_key(value: Any) -> Tuple[bool, ConditionalEvaluationKey | Exception]: ...
DecisionDefinitionId = NewType('DecisionDefinitionId', str)
def lift_decision_definition_id(value: Any) -> DecisionDefinitionId: ...
def try_lift_decision_definition_id(value: Any) -> Tuple[bool, DecisionDefinitionId | Exception]: ...
DecisionDefinitionKey = NewType('DecisionDefinitionKey', str)
def lift_decision_definition_key(value: Any) -> DecisionDefinitionKey: ...
def try_lift_decision_definition_key(value: Any) -> Tuple[bool, DecisionDefinitionKey | Exception]: ...
DecisionEvaluationInstanceKey = NewType('DecisionEvaluationInstanceKey', str)
def lift_decision_evaluation_instance_key(value: Any) -> DecisionEvaluationInstanceKey: ...
def try_lift_decision_evaluation_instance_key(value: Any) -> Tuple[bool, DecisionEvaluationInstanceKey | Exception]: ...
DecisionEvaluationKey = NewType('DecisionEvaluationKey', str)
def lift_decision_evaluation_key(value: Any) -> DecisionEvaluationKey: ...
def try_lift_decision_evaluation_key(value: Any) -> Tuple[bool, DecisionEvaluationKey | Exception]: ...
DecisionInstanceKey = NewType('DecisionInstanceKey', str)
def lift_decision_instance_key(value: Any) -> DecisionInstanceKey: ...
def try_lift_decision_instance_key(value: Any) -> Tuple[bool, DecisionInstanceKey | Exception]: ...
DecisionRequirementsKey = NewType('DecisionRequirementsKey', str)
def lift_decision_requirements_key(value: Any) -> DecisionRequirementsKey: ...
def try_lift_decision_requirements_key(value: Any) -> Tuple[bool, DecisionRequirementsKey | Exception]: ...
DeploymentKey = NewType('DeploymentKey', str)
def lift_deployment_key(value: Any) -> DeploymentKey: ...
def try_lift_deployment_key(value: Any) -> Tuple[bool, DeploymentKey | Exception]: ...
DocumentId = NewType('DocumentId', str)
def lift_document_id(value: Any) -> DocumentId: ...
def try_lift_document_id(value: Any) -> Tuple[bool, DocumentId | Exception]: ...
ElementId = NewType('ElementId', str)
def lift_element_id(value: Any) -> ElementId: ...
def try_lift_element_id(value: Any) -> Tuple[bool, ElementId | Exception]: ...
ElementInstanceKey = NewType('ElementInstanceKey', str)
def lift_element_instance_key(value: Any) -> ElementInstanceKey: ...
def try_lift_element_instance_key(value: Any) -> Tuple[bool, ElementInstanceKey | Exception]: ...
EndCursor = NewType('EndCursor', str)
def lift_end_cursor(value: Any) -> EndCursor: ...
def try_lift_end_cursor(value: Any) -> Tuple[bool, EndCursor | Exception]: ...
FormId = NewType('FormId', str)
def lift_form_id(value: Any) -> FormId: ...
def try_lift_form_id(value: Any) -> Tuple[bool, FormId | Exception]: ...
FormKey = NewType('FormKey', str)
def lift_form_key(value: Any) -> FormKey: ...
def try_lift_form_key(value: Any) -> Tuple[bool, FormKey | Exception]: ...
GlobalListenerId = NewType('GlobalListenerId', str)
def lift_global_listener_id(value: Any) -> GlobalListenerId: ...
def try_lift_global_listener_id(value: Any) -> Tuple[bool, GlobalListenerId | Exception]: ...
IncidentKey = NewType('IncidentKey', str)
def lift_incident_key(value: Any) -> IncidentKey: ...
def try_lift_incident_key(value: Any) -> Tuple[bool, IncidentKey | Exception]: ...
JobKey = NewType('JobKey', str)
def lift_job_key(value: Any) -> JobKey: ...
def try_lift_job_key(value: Any) -> Tuple[bool, JobKey | Exception]: ...
MessageKey = NewType('MessageKey', str)
def lift_message_key(value: Any) -> MessageKey: ...
def try_lift_message_key(value: Any) -> Tuple[bool, MessageKey | Exception]: ...
MessageSubscriptionKey = NewType('MessageSubscriptionKey', str)
def lift_message_subscription_key(value: Any) -> MessageSubscriptionKey: ...
def try_lift_message_subscription_key(value: Any) -> Tuple[bool, MessageSubscriptionKey | Exception]: ...
ProcessDefinitionId = NewType('ProcessDefinitionId', str)
def lift_process_definition_id(value: Any) -> ProcessDefinitionId: ...
def try_lift_process_definition_id(value: Any) -> Tuple[bool, ProcessDefinitionId | Exception]: ...
ProcessDefinitionKey = NewType('ProcessDefinitionKey', str)
def lift_process_definition_key(value: Any) -> ProcessDefinitionKey: ...
def try_lift_process_definition_key(value: Any) -> Tuple[bool, ProcessDefinitionKey | Exception]: ...
ProcessInstanceKey = NewType('ProcessInstanceKey', str)
def lift_process_instance_key(value: Any) -> ProcessInstanceKey: ...
def try_lift_process_instance_key(value: Any) -> Tuple[bool, ProcessInstanceKey | Exception]: ...
RootProcessInstanceKey = NewType('RootProcessInstanceKey', str)
def lift_root_process_instance_key(value: Any) -> RootProcessInstanceKey: ...
def try_lift_root_process_instance_key(value: Any) -> Tuple[bool, RootProcessInstanceKey | Exception]: ...
ScopeKey = NewType('ScopeKey', str)
def lift_scope_key(value: Any) -> ScopeKey: ...
def try_lift_scope_key(value: Any) -> Tuple[bool, ScopeKey | Exception]: ...
SignalKey = NewType('SignalKey', str)
def lift_signal_key(value: Any) -> SignalKey: ...
def try_lift_signal_key(value: Any) -> Tuple[bool, SignalKey | Exception]: ...
StartCursor = NewType('StartCursor', str)
def lift_start_cursor(value: Any) -> StartCursor: ...
def try_lift_start_cursor(value: Any) -> Tuple[bool, StartCursor | Exception]: ...
Tag = NewType('Tag', str)
def lift_tag(value: Any) -> Tag: ...
def try_lift_tag(value: Any) -> Tuple[bool, Tag | Exception]: ...
TenantId = NewType('TenantId', str)
def lift_tenant_id(value: Any) -> TenantId: ...
def try_lift_tenant_id(value: Any) -> Tuple[bool, TenantId | Exception]: ...
UserTaskKey = NewType('UserTaskKey', str)
def lift_user_task_key(value: Any) -> UserTaskKey: ...
def try_lift_user_task_key(value: Any) -> Tuple[bool, UserTaskKey | Exception]: ...
Username = NewType('Username', str)
def lift_username(value: Any) -> Username: ...
def try_lift_username(value: Any) -> Tuple[bool, Username | Exception]: ...
VariableKey = NewType('VariableKey', str)
def lift_variable_key(value: Any) -> VariableKey: ...
def try_lift_variable_key(value: Any) -> Tuple[bool, VariableKey | Exception]: ...
__all__ = ['AuditLogEntityKey', 'AuditLogKey', 'AuthorizationKey', 'BatchOperationKey', 'ConditionalEvaluationKey', 'DecisionDefinitionId', 'DecisionDefinitionKey', 'DecisionEvaluationInstanceKey', 'DecisionEvaluationKey', 'DecisionInstanceKey', 'DecisionRequirementsKey', 'DeploymentKey', 'DocumentId', 'ElementId', 'ElementInstanceKey', 'EndCursor', 'FormId', 'FormKey', 'GlobalListenerId', 'IncidentKey', 'JobKey', 'MessageKey', 'MessageSubscriptionKey', 'ProcessDefinitionId', 'ProcessDefinitionKey', 'ProcessInstanceKey', 'RootProcessInstanceKey', 'ScopeKey', 'SignalKey', 'StartCursor', 'Tag', 'TenantId', 'UserTaskKey', 'Username', 'VariableKey', 'lift_audit_log_entity_key', 'lift_audit_log_key', 'lift_authorization_key', 'lift_batch_operation_key', 'lift_conditional_evaluation_key', 'lift_decision_definition_id', 'lift_decision_definition_key', 'lift_decision_evaluation_instance_key', 'lift_decision_evaluation_key', 'lift_decision_instance_key', 'lift_decision_requirements_key', 'lift_deployment_key', 'lift_document_id', 'lift_element_id', 'lift_element_instance_key', 'lift_end_cursor', 'lift_form_id', 'lift_form_key', 'lift_global_listener_id', 'lift_incident_key', 'lift_job_key', 'lift_message_key', 'lift_message_subscription_key', 'lift_process_definition_id', 'lift_process_definition_key', 'lift_process_instance_key', 'lift_root_process_instance_key', 'lift_scope_key', 'lift_signal_key', 'lift_start_cursor', 'lift_tag', 'lift_tenant_id', 'lift_user_task_key', 'lift_username', 'lift_variable_key', 'try_lift_audit_log_entity_key', 'try_lift_audit_log_key', 'try_lift_authorization_key', 'try_lift_batch_operation_key', 'try_lift_conditional_evaluation_key', 'try_lift_decision_definition_id', 'try_lift_decision_definition_key', 'try_lift_decision_evaluation_instance_key', 'try_lift_decision_evaluation_key', 'try_lift_decision_instance_key', 'try_lift_decision_requirements_key', 'try_lift_deployment_key', 'try_lift_document_id', 'try_lift_element_id', 'try_lift_element_instance_key', 'try_lift_end_cursor', 'try_lift_form_id', 'try_lift_form_key', 'try_lift_global_listener_id', 'try_lift_incident_key', 'try_lift_job_key', 'try_lift_message_key', 'try_lift_message_subscription_key', 'try_lift_process_definition_id', 'try_lift_process_definition_key', 'try_lift_process_instance_key', 'try_lift_root_process_instance_key', 'try_lift_scope_key', 'try_lift_signal_key', 'try_lift_start_cursor', 'try_lift_tag', 'try_lift_tenant_id', 'try_lift_user_task_key', 'try_lift_username', 'try_lift_variable_key']
