from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.message_correlation_request import MessageCorrelationRequest
from ...models.message_correlation_result import MessageCorrelationResult
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(body: MessageCorrelationRequest) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> MessageCorrelationResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[MessageCorrelationResult | ProblemDetail]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: MessageCorrelationRequest) -> Response[MessageCorrelationResult | ProblemDetail]: ...
def sync(client: AuthenticatedClient | Client, body: MessageCorrelationRequest, **kwargs: Any) -> MessageCorrelationResult: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: MessageCorrelationRequest) -> Response[MessageCorrelationResult | ProblemDetail]: ...
async def asyncio(client: AuthenticatedClient | Client, body: MessageCorrelationRequest, **kwargs: Any) -> MessageCorrelationResult: ...
