from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.message_publication_request import MessagePublicationRequest
from ...models.message_publication_result import MessagePublicationResult
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(body: MessagePublicationRequest) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> MessagePublicationResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[MessagePublicationResult | ProblemDetail]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: MessagePublicationRequest) -> Response[MessagePublicationResult | ProblemDetail]: ...
def sync(client: AuthenticatedClient | Client, body: MessagePublicationRequest, **kwargs: Any) -> MessagePublicationResult: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: MessagePublicationRequest) -> Response[MessagePublicationResult | ProblemDetail]: ...
async def asyncio(client: AuthenticatedClient | Client, body: MessagePublicationRequest, **kwargs: Any) -> MessagePublicationResult: ...
