from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.cluster_variable_result import ClusterVariableResult
from ...models.create_cluster_variable_request import CreateClusterVariableRequest
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(body: CreateClusterVariableRequest) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ClusterVariableResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ClusterVariableResult | ProblemDetail]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: CreateClusterVariableRequest) -> Response[ClusterVariableResult | ProblemDetail]: ...
def sync(client: AuthenticatedClient | Client, body: CreateClusterVariableRequest, **kwargs: Any) -> ClusterVariableResult: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: CreateClusterVariableRequest) -> Response[ClusterVariableResult | ProblemDetail]: ...
async def asyncio(client: AuthenticatedClient | Client, body: CreateClusterVariableRequest, **kwargs: Any) -> ClusterVariableResult: ...
