from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.problem_detail import ProblemDetail
from ...models.search_message_subscriptions_data import SearchMessageSubscriptionsData
from ...models.search_message_subscriptions_response_200 import SearchMessageSubscriptionsResponse200
from ...types import UNSET, Response, Unset
def _get_kwargs(body: SearchMessageSubscriptionsData | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ProblemDetail | SearchMessageSubscriptionsResponse200 | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ProblemDetail | SearchMessageSubscriptionsResponse200]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: SearchMessageSubscriptionsData | Unset = UNSET) -> Response[ProblemDetail | SearchMessageSubscriptionsResponse200]: ...
def sync(client: AuthenticatedClient | Client, body: SearchMessageSubscriptionsData | Unset = UNSET, **kwargs: Any) -> SearchMessageSubscriptionsResponse200: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: SearchMessageSubscriptionsData | Unset = UNSET) -> Response[ProblemDetail | SearchMessageSubscriptionsResponse200]: ...
async def asyncio(client: AuthenticatedClient | Client, body: SearchMessageSubscriptionsData | Unset = UNSET, **kwargs: Any) -> SearchMessageSubscriptionsResponse200: ...
