from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.message_subscription_search_query import MessageSubscriptionSearchQuery
from ...models.message_subscription_search_query_result import MessageSubscriptionSearchQueryResult
from ...models.problem_detail import ProblemDetail
from ...types import UNSET, Response, Unset
def _get_kwargs(body: MessageSubscriptionSearchQuery | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> MessageSubscriptionSearchQueryResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[MessageSubscriptionSearchQueryResult | ProblemDetail]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: MessageSubscriptionSearchQuery | Unset = UNSET) -> Response[MessageSubscriptionSearchQueryResult | ProblemDetail]: ...
def sync(client: AuthenticatedClient | Client, body: MessageSubscriptionSearchQuery | Unset = UNSET, **kwargs: Any) -> MessageSubscriptionSearchQueryResult: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: MessageSubscriptionSearchQuery | Unset = UNSET) -> Response[MessageSubscriptionSearchQueryResult | ProblemDetail]: ...
async def asyncio(client: AuthenticatedClient | Client, body: MessageSubscriptionSearchQuery | Unset = UNSET, **kwargs: Any) -> MessageSubscriptionSearchQueryResult: ...
