version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "stable/9"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "stable/9"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
