from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.group_create_request import GroupCreateRequest
from ...models.group_create_result import GroupCreateResult
from ...models.problem_detail import ProblemDetail
from ...types import UNSET, Response, Unset
def _get_kwargs(body: GroupCreateRequest | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> GroupCreateResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[GroupCreateResult | ProblemDetail]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: GroupCreateRequest | Unset = UNSET) -> Response[GroupCreateResult | ProblemDetail]: ...
def sync(client: AuthenticatedClient | Client, body: GroupCreateRequest | Unset = UNSET, **kwargs: Any) -> GroupCreateResult: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: GroupCreateRequest | Unset = UNSET) -> Response[GroupCreateResult | ProblemDetail]: ...
async def asyncio(client: AuthenticatedClient | Client, body: GroupCreateRequest | Unset = UNSET, **kwargs: Any) -> GroupCreateResult: ...
