from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.mapping_rule_search_query_request import MappingRuleSearchQueryRequest
from ...models.problem_detail import ProblemDetail
from ...models.search_mapping_rules_for_group_response_200 import SearchMappingRulesForGroupResponse200
from ...types import UNSET, Response, Unset
def _get_kwargs(group_id: str, body: MappingRuleSearchQueryRequest | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ProblemDetail | SearchMappingRulesForGroupResponse200 | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ProblemDetail | SearchMappingRulesForGroupResponse200]: ...
def sync_detailed(group_id: str, client: AuthenticatedClient | Client, body: MappingRuleSearchQueryRequest | Unset = UNSET) -> Response[ProblemDetail | SearchMappingRulesForGroupResponse200]: ...
def sync(group_id: str, client: AuthenticatedClient | Client, body: MappingRuleSearchQueryRequest | Unset = UNSET, **kwargs: Any) -> SearchMappingRulesForGroupResponse200: ...
async def asyncio_detailed(group_id: str, client: AuthenticatedClient | Client, body: MappingRuleSearchQueryRequest | Unset = UNSET) -> Response[ProblemDetail | SearchMappingRulesForGroupResponse200]: ...
async def asyncio(group_id: str, client: AuthenticatedClient | Client, body: MappingRuleSearchQueryRequest | Unset = UNSET, **kwargs: Any) -> SearchMappingRulesForGroupResponse200: ...
