from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.problem_detail import ProblemDetail
from ...models.search_clients_for_group_data import SearchClientsForGroupData
from ...models.search_clients_for_group_response_200 import SearchClientsForGroupResponse200
from ...types import UNSET, Response, Unset
def _get_kwargs(group_id: str, body: SearchClientsForGroupData | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ProblemDetail | SearchClientsForGroupResponse200 | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ProblemDetail | SearchClientsForGroupResponse200]: ...
def sync_detailed(group_id: str, client: AuthenticatedClient | Client, body: SearchClientsForGroupData | Unset = UNSET) -> Response[ProblemDetail | SearchClientsForGroupResponse200]: ...
def sync(group_id: str, client: AuthenticatedClient | Client, body: SearchClientsForGroupData | Unset = UNSET, **kwargs: Any) -> SearchClientsForGroupResponse200: ...
async def asyncio_detailed(group_id: str, client: AuthenticatedClient | Client, body: SearchClientsForGroupData | Unset = UNSET) -> Response[ProblemDetail | SearchClientsForGroupResponse200]: ...
async def asyncio(group_id: str, client: AuthenticatedClient | Client, body: SearchClientsForGroupData | Unset = UNSET, **kwargs: Any) -> SearchClientsForGroupResponse200: ...
