"""Acceptance tests for the synthesized get_status convenience wrapper.

get_status is a body-less endpoint (GET /status → 204/503) whose sync/asyncio
functions are synthesized by the flatten-client hook rather than generated by
openapi-python-client.  These tests verify the synthesized endpoint module and
the CamundaClient facade method both exist and behave correctly.
"""

import httpx
import pytest

from camunda_orchestration_sdk import CamundaClient, CamundaAsyncClient
from camunda_orchestration_sdk.api.cluster import get_status
from camunda_orchestration_sdk.errors import ServiceUnavailableError


# ---------------------------------------------------------------------------
# Module-level: the synthesized convenience functions should be importable
# ---------------------------------------------------------------------------

def test_get_status_sync_function_exists():
    """The flatten-client hook should synthesize a ``sync`` convenience function."""
    assert callable(getattr(get_status, "sync", None))


def test_get_status_asyncio_function_exists():
    """The flatten-client hook should synthesize an ``asyncio`` convenience function."""
    assert callable(getattr(get_status, "asyncio", None))


# ---------------------------------------------------------------------------
# CamundaClient facade
# ---------------------------------------------------------------------------

def test_camunda_client_has_get_status_method():
    """CamundaClient should expose a ``get_status`` method on the flat facade."""
    client = CamundaClient()
    assert hasattr(client, "get_status")
    assert callable(client.get_status)  # pyright: ignore[reportUnknownMemberType,reportUnknownArgumentType,reportAttributeAccessIssue]


# ---------------------------------------------------------------------------
# Behaviour: 204 → None, 503 → raises ServiceUnavailableError
# ---------------------------------------------------------------------------

def _mock_transport(status: int) -> httpx.MockTransport:
    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(status_code=status)
    return httpx.MockTransport(handler)


def test_get_status_returns_none_on_204():
    """A 204 response (healthy) should return None without raising."""
    client = CamundaClient(httpx_args={"transport": _mock_transport(204)})
    result = client.get_status()  # pyright: ignore[reportUnknownMemberType,reportUnknownVariableType,reportAttributeAccessIssue]
    assert result is None


def test_get_status_raises_on_503():
    """A 503 response (unhealthy) should raise ServiceUnavailableError with operation_id."""
    client = CamundaClient(httpx_args={"transport": _mock_transport(503)})
    with pytest.raises(ServiceUnavailableError) as exc_info:
        client.get_status()  # pyright: ignore[reportUnknownMemberType,reportAttributeAccessIssue]
    assert exc_info.value.status_code == 503
    assert exc_info.value.operation_id == "get_status"


# ---------------------------------------------------------------------------
# Async behaviour
# ---------------------------------------------------------------------------

@pytest.mark.asyncio
async def test_async_get_status_returns_none_on_204():
    """Async: A 204 response (healthy) should return None without raising."""
    client = CamundaAsyncClient(httpx_args={"transport": _mock_transport(204)})
    result = await client.get_status()  # pyright: ignore[reportUnknownMemberType,reportUnknownVariableType,reportAttributeAccessIssue]
    assert result is None


@pytest.mark.asyncio
async def test_async_get_status_raises_on_503():
    """Async: A 503 response (unhealthy) should raise ServiceUnavailableError."""
    client = CamundaAsyncClient(httpx_args={"transport": _mock_transport(503)})
    with pytest.raises(ServiceUnavailableError) as exc_info:
        await client.get_status()  # pyright: ignore[reportUnknownMemberType,reportAttributeAccessIssue]
    assert exc_info.value.status_code == 503
    assert exc_info.value.operation_id == "get_status"
