from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.decision_evaluation_by_id import DecisionEvaluationByID
from ...models.decision_evaluation_by_key import DecisionEvaluationByKey
from ...models.evaluate_decision_result import EvaluateDecisionResult
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(body: DecisionEvaluationByID | DecisionEvaluationByKey) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> EvaluateDecisionResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[EvaluateDecisionResult | ProblemDetail]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: DecisionEvaluationByID | DecisionEvaluationByKey) -> Response[EvaluateDecisionResult | ProblemDetail]: ...
def sync(client: AuthenticatedClient | Client, body: DecisionEvaluationByID | DecisionEvaluationByKey, **kwargs: Any) -> EvaluateDecisionResult: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: DecisionEvaluationByID | DecisionEvaluationByKey) -> Response[EvaluateDecisionResult | ProblemDetail]: ...
async def asyncio(client: AuthenticatedClient | Client, body: DecisionEvaluationByID | DecisionEvaluationByKey, **kwargs: Any) -> EvaluateDecisionResult: ...
