from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.decision_definition_search_query import DecisionDefinitionSearchQuery
from ...models.decision_definition_search_query_result import DecisionDefinitionSearchQueryResult
from ...models.problem_detail import ProblemDetail
from ...types import UNSET, Response, Unset
def _get_kwargs(body: DecisionDefinitionSearchQuery | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> DecisionDefinitionSearchQueryResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[DecisionDefinitionSearchQueryResult | ProblemDetail]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: DecisionDefinitionSearchQuery | Unset = UNSET) -> Response[DecisionDefinitionSearchQueryResult | ProblemDetail]: ...
def sync(client: AuthenticatedClient | Client, body: DecisionDefinitionSearchQuery | Unset = UNSET, **kwargs: Any) -> DecisionDefinitionSearchQueryResult: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: DecisionDefinitionSearchQuery | Unset = UNSET) -> Response[DecisionDefinitionSearchQueryResult | ProblemDetail]: ...
async def asyncio(client: AuthenticatedClient | Client, body: DecisionDefinitionSearchQuery | Unset = UNSET, **kwargs: Any) -> DecisionDefinitionSearchQueryResult: ...
