from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.problem_detail import ProblemDetail
from ...models.variable_result import VariableResult
from ...types import Response
def _get_kwargs(variable_key: str) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ProblemDetail | VariableResult | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ProblemDetail | VariableResult]: ...
def sync_detailed(variable_key: str, client: AuthenticatedClient | Client) -> Response[ProblemDetail | VariableResult]: ...
def sync(variable_key: str, client: AuthenticatedClient | Client, **kwargs: Any) -> VariableResult: ...
async def asyncio_detailed(variable_key: str, client: AuthenticatedClient | Client) -> Response[ProblemDetail | VariableResult]: ...
async def asyncio(variable_key: str, client: AuthenticatedClient | Client, **kwargs: Any) -> VariableResult: ...
