from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.problem_detail import ProblemDetail
from ...models.role_result import RoleResult
from ...types import Response
def _get_kwargs(role_id: str) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ProblemDetail | RoleResult | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ProblemDetail | RoleResult]: ...
def sync_detailed(role_id: str, client: AuthenticatedClient | Client) -> Response[ProblemDetail | RoleResult]: ...
def sync(role_id: str, client: AuthenticatedClient | Client, **kwargs: Any) -> RoleResult: ...
async def asyncio_detailed(role_id: str, client: AuthenticatedClient | Client) -> Response[ProblemDetail | RoleResult]: ...
async def asyncio(role_id: str, client: AuthenticatedClient | Client, **kwargs: Any) -> RoleResult: ...
