from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.problem_detail import ProblemDetail
from ...models.search_clients_for_role_data import SearchClientsForRoleData
from ...models.tenant_client_search_result import TenantClientSearchResult
from ...types import UNSET, Response, Unset
def _get_kwargs(role_id: str, body: SearchClientsForRoleData | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ProblemDetail | TenantClientSearchResult | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ProblemDetail | TenantClientSearchResult]: ...
def sync_detailed(role_id: str, client: AuthenticatedClient | Client, body: SearchClientsForRoleData | Unset = UNSET) -> Response[ProblemDetail | TenantClientSearchResult]: ...
def sync(role_id: str, client: AuthenticatedClient | Client, body: SearchClientsForRoleData | Unset = UNSET, **kwargs: Any) -> TenantClientSearchResult: ...
async def asyncio_detailed(role_id: str, client: AuthenticatedClient | Client, body: SearchClientsForRoleData | Unset = UNSET) -> Response[ProblemDetail | TenantClientSearchResult]: ...
async def asyncio(role_id: str, client: AuthenticatedClient | Client, body: SearchClientsForRoleData | Unset = UNSET, **kwargs: Any) -> TenantClientSearchResult: ...
