from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.problem_detail import ProblemDetail
from ...models.search_clients_for_role_data import SearchClientsForRoleData
from ...models.search_clients_for_role_response_200 import SearchClientsForRoleResponse200
from ...types import UNSET, Response, Unset
def _get_kwargs(role_id: str, body: SearchClientsForRoleData | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ProblemDetail | SearchClientsForRoleResponse200 | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ProblemDetail | SearchClientsForRoleResponse200]: ...
def sync_detailed(role_id: str, client: AuthenticatedClient | Client, body: SearchClientsForRoleData | Unset = UNSET) -> Response[ProblemDetail | SearchClientsForRoleResponse200]: ...
def sync(role_id: str, client: AuthenticatedClient | Client, body: SearchClientsForRoleData | Unset = UNSET, **kwargs: Any) -> SearchClientsForRoleResponse200: ...
async def asyncio_detailed(role_id: str, client: AuthenticatedClient | Client, body: SearchClientsForRoleData | Unset = UNSET) -> Response[ProblemDetail | SearchClientsForRoleResponse200]: ...
async def asyncio(role_id: str, client: AuthenticatedClient | Client, body: SearchClientsForRoleData | Unset = UNSET, **kwargs: Any) -> SearchClientsForRoleResponse200: ...
