from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.mapping_rule_search_query_request import MappingRuleSearchQueryRequest
from ...models.problem_detail import ProblemDetail
from ...models.search_mapping_rules_for_role_response_200 import SearchMappingRulesForRoleResponse200
from ...types import UNSET, Response, Unset
def _get_kwargs(role_id: str, body: MappingRuleSearchQueryRequest | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ProblemDetail | SearchMappingRulesForRoleResponse200 | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ProblemDetail | SearchMappingRulesForRoleResponse200]: ...
def sync_detailed(role_id: str, client: AuthenticatedClient | Client, body: MappingRuleSearchQueryRequest | Unset = UNSET) -> Response[ProblemDetail | SearchMappingRulesForRoleResponse200]: ...
def sync(role_id: str, client: AuthenticatedClient | Client, body: MappingRuleSearchQueryRequest | Unset = UNSET, **kwargs: Any) -> SearchMappingRulesForRoleResponse200: ...
async def asyncio_detailed(role_id: str, client: AuthenticatedClient | Client, body: MappingRuleSearchQueryRequest | Unset = UNSET) -> Response[ProblemDetail | SearchMappingRulesForRoleResponse200]: ...
async def asyncio(role_id: str, client: AuthenticatedClient | Client, body: MappingRuleSearchQueryRequest | Unset = UNSET, **kwargs: Any) -> SearchMappingRulesForRoleResponse200: ...
