from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.problem_detail import ProblemDetail
from ...models.search_users_for_role_data import SearchUsersForRoleData
from ...models.search_users_for_role_response_200 import SearchUsersForRoleResponse200
from ...types import UNSET, Response, Unset
def _get_kwargs(role_id: str, body: SearchUsersForRoleData | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ProblemDetail | SearchUsersForRoleResponse200 | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ProblemDetail | SearchUsersForRoleResponse200]: ...
def sync_detailed(role_id: str, client: AuthenticatedClient | Client, body: SearchUsersForRoleData | Unset = UNSET) -> Response[ProblemDetail | SearchUsersForRoleResponse200]: ...
def sync(role_id: str, client: AuthenticatedClient | Client, body: SearchUsersForRoleData | Unset = UNSET, **kwargs: Any) -> SearchUsersForRoleResponse200: ...
async def asyncio_detailed(role_id: str, client: AuthenticatedClient | Client, body: SearchUsersForRoleData | Unset = UNSET) -> Response[ProblemDetail | SearchUsersForRoleResponse200]: ...
async def asyncio(role_id: str, client: AuthenticatedClient | Client, body: SearchUsersForRoleData | Unset = UNSET, **kwargs: Any) -> SearchUsersForRoleResponse200: ...
