from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.problem_detail import ProblemDetail
from ...models.topology_response import TopologyResponse
from ...types import Response
def _get_kwargs() -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ProblemDetail | TopologyResponse | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ProblemDetail | TopologyResponse]: ...
def sync_detailed(client: AuthenticatedClient | Client) -> Response[ProblemDetail | TopologyResponse]: ...
def sync(client: AuthenticatedClient | Client, **kwargs: Any) -> TopologyResponse: ...
async def asyncio_detailed(client: AuthenticatedClient | Client) -> Response[ProblemDetail | TopologyResponse]: ...
async def asyncio(client: AuthenticatedClient | Client, **kwargs: Any) -> TopologyResponse: ...
