from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...types import Response

def _get_kwargs() -> dict[str, Any]: ...
def _parse_response(
    client: AuthenticatedClient | Client, response: httpx.Response
) -> Any | None: ...
def _build_response(
    client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Any]: ...
def sync_detailed(client: AuthenticatedClient | Client) -> Response[Any]: ...
async def asyncio_detailed(client: AuthenticatedClient | Client) -> Response[Any]: ...
