from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.get_process_instance_statistics_response_200 import GetProcessInstanceStatisticsResponse200
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(process_instance_key: str) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> GetProcessInstanceStatisticsResponse200 | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[GetProcessInstanceStatisticsResponse200 | ProblemDetail]: ...
def sync_detailed(process_instance_key: str, client: AuthenticatedClient | Client) -> Response[GetProcessInstanceStatisticsResponse200 | ProblemDetail]: ...
def sync(process_instance_key: str, client: AuthenticatedClient | Client, **kwargs: Any) -> GetProcessInstanceStatisticsResponse200: ...
async def asyncio_detailed(process_instance_key: str, client: AuthenticatedClient | Client) -> Response[GetProcessInstanceStatisticsResponse200 | ProblemDetail]: ...
async def asyncio(process_instance_key: str, client: AuthenticatedClient | Client, **kwargs: Any) -> GetProcessInstanceStatisticsResponse200: ...
