from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.problem_detail import ProblemDetail
from ...models.process_instance_sequence_flows_query_result import ProcessInstanceSequenceFlowsQueryResult
from ...types import Response
def _get_kwargs(process_instance_key: str) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ProblemDetail | ProcessInstanceSequenceFlowsQueryResult | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ProblemDetail | ProcessInstanceSequenceFlowsQueryResult]: ...
def sync_detailed(process_instance_key: str, client: AuthenticatedClient | Client) -> Response[ProblemDetail | ProcessInstanceSequenceFlowsQueryResult]: ...
def sync(process_instance_key: str, client: AuthenticatedClient | Client, **kwargs: Any) -> ProcessInstanceSequenceFlowsQueryResult: ...
async def asyncio_detailed(process_instance_key: str, client: AuthenticatedClient | Client) -> Response[ProblemDetail | ProcessInstanceSequenceFlowsQueryResult]: ...
async def asyncio(process_instance_key: str, client: AuthenticatedClient | Client, **kwargs: Any) -> ProcessInstanceSequenceFlowsQueryResult: ...
