from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.migrate_process_instance_data import MigrateProcessInstanceData
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(process_instance_key: str, body: MigrateProcessInstanceData) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Any | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[Any | ProblemDetail]: ...
def sync_detailed(process_instance_key: str, client: AuthenticatedClient | Client, body: MigrateProcessInstanceData) -> Response[Any | ProblemDetail]: ...
def sync(process_instance_key: str, client: AuthenticatedClient | Client, body: MigrateProcessInstanceData, **kwargs: Any) -> None: ...
async def asyncio_detailed(process_instance_key: str, client: AuthenticatedClient | Client, body: MigrateProcessInstanceData) -> Response[Any | ProblemDetail]: ...
async def asyncio(process_instance_key: str, client: AuthenticatedClient | Client, body: MigrateProcessInstanceData, **kwargs: Any) -> None: ...
