from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.batch_operation_created_result import BatchOperationCreatedResult
from ...models.problem_detail import ProblemDetail
from ...models.process_instance_migration_batch_operation_request import ProcessInstanceMigrationBatchOperationRequest
from ...types import Response
def _get_kwargs(body: ProcessInstanceMigrationBatchOperationRequest) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> BatchOperationCreatedResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[BatchOperationCreatedResult | ProblemDetail]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: ProcessInstanceMigrationBatchOperationRequest) -> Response[BatchOperationCreatedResult | ProblemDetail]: ...
def sync(client: AuthenticatedClient | Client, body: ProcessInstanceMigrationBatchOperationRequest, **kwargs: Any) -> BatchOperationCreatedResult: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: ProcessInstanceMigrationBatchOperationRequest) -> Response[BatchOperationCreatedResult | ProblemDetail]: ...
async def asyncio(client: AuthenticatedClient | Client, body: ProcessInstanceMigrationBatchOperationRequest, **kwargs: Any) -> BatchOperationCreatedResult: ...
