from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.problem_detail import ProblemDetail
from ...models.process_instance_search_query import ProcessInstanceSearchQuery
from ...models.process_instance_search_query_result import ProcessInstanceSearchQueryResult
from ...types import UNSET, Response, Unset
def _get_kwargs(body: ProcessInstanceSearchQuery | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ProblemDetail | ProcessInstanceSearchQueryResult | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ProblemDetail | ProcessInstanceSearchQueryResult]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: ProcessInstanceSearchQuery | Unset = UNSET) -> Response[ProblemDetail | ProcessInstanceSearchQueryResult]: ...
def sync(client: AuthenticatedClient | Client, body: ProcessInstanceSearchQuery | Unset = UNSET, **kwargs: Any) -> ProcessInstanceSearchQueryResult: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: ProcessInstanceSearchQuery | Unset = UNSET) -> Response[ProblemDetail | ProcessInstanceSearchQueryResult]: ...
async def asyncio(client: AuthenticatedClient | Client, body: ProcessInstanceSearchQuery | Unset = UNSET, **kwargs: Any) -> ProcessInstanceSearchQueryResult: ...
