from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.problem_detail import ProblemDetail
from ...models.search_process_instances_data import SearchProcessInstancesData
from ...models.search_process_instances_response_200 import SearchProcessInstancesResponse200
from ...types import UNSET, Response, Unset
def _get_kwargs(body: SearchProcessInstancesData | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ProblemDetail | SearchProcessInstancesResponse200 | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ProblemDetail | SearchProcessInstancesResponse200]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: SearchProcessInstancesData | Unset = UNSET) -> Response[ProblemDetail | SearchProcessInstancesResponse200]: ...
def sync(client: AuthenticatedClient | Client, body: SearchProcessInstancesData | Unset = UNSET, **kwargs: Any) -> SearchProcessInstancesResponse200: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: SearchProcessInstancesData | Unset = UNSET) -> Response[ProblemDetail | SearchProcessInstancesResponse200]: ...
async def asyncio(client: AuthenticatedClient | Client, body: SearchProcessInstancesData | Unset = UNSET, **kwargs: Any) -> SearchProcessInstancesResponse200: ...
