from __future__ import annotations

from pathlib import Path
from dataclasses import dataclass
from typing import Any, Mapping, Protocol, runtime_checkable
import httpx
from .logging import SdkLogger
_LOG_LEVEL_ORDER: dict[str, int] = {
    "silent": 0,
    "error": 1,
    "warn": 2,
    "info": 3,
    "debug": 4,
    "trace": 5,
    "silly": 6,
}
_SAAS_OAUTH_HOST = "login.cloud.camunda.io"
_SAAS_401_COOLDOWN_S_DEFAULT = 30.0
_TARPIT_FILENAME_SALT = "camunda-oauth-tarpit-filename-salt-v1"
def _is_saas_oauth_url(oauth_url: str) -> bool: ...
def _safe_filename_component(value: str) -> str: ...
def _hash_secret_for_filename(secret: str) -> str: ...
def _ensure_dir(path: Path, logger: SdkLogger | None = None) -> bool: ...
def _should_log_http(log_level: str | None) -> bool: ...
def _should_log_http_body(log_level: str | None) -> bool: ...
@runtime_checkable
class AuthProvider(Protocol):
    def get_headers(self) -> Mapping[str, str]: ...
@runtime_checkable
class AsyncAuthProvider(Protocol):
    async def aget_headers(self) -> Mapping[str, str]: ...
class NullAuthProvider:
    def get_headers(self) -> dict[str, str]: ...
def _resolve_auth_headers(provider: object) -> Mapping[str, str]: ...
async def _resolve_async_auth_headers(provider: object) -> Mapping[str, str]: ...
class BasicAuthProvider:
    def __init__(self, username: str, password: str): ...
    def get_headers(self) -> Mapping[str, str]: ...
@dataclass
class _OAuthToken:
    access_token: str
    expires_at_epoch_s: float
class OAuthClientCredentialsAuthProvider:
    def __init__(self, oauth_url: str, client_id: str, client_secret: str, audience: str, cache_dir: str | None = None, disk_cache_disable: bool = False, saas_401_cooldown_s: float = _SAAS_401_COOLDOWN_S_DEFAULT, transport: httpx.BaseTransport | None = None, timeout: float | None = None, logger: SdkLogger | None = None): ...
    def close(self) -> None: ...
    def __enter__(self) -> "OAuthClientCredentialsAuthProvider": ...
    def __exit__(self, *args: Any, **kwargs: Any) -> None: ...
    def _token_cache_file(self) -> Path | None: ...
    def _tarpit_file(self) -> Path | None: ...
    def _now(self) -> float: ...
    def _is_valid(self, token: _OAuthToken) -> bool: ...
    def _try_load_file_cached_token(self) -> _OAuthToken | None: ...
    def _try_save_file_cached_token(self, token: _OAuthToken) -> None: ...
    def _is_tarpitted(self) -> bool: ...
    def _create_tarpit_file(self, reason: str) -> None: ...
    def _fetch_token(self) -> _OAuthToken: ...
    def get_headers(self) -> Mapping[str, str]: ...
class AsyncOAuthClientCredentialsAuthProvider:
    def __init__(self, oauth_url: str, client_id: str, client_secret: str, audience: str, cache_dir: str | None = None, disk_cache_disable: bool = False, saas_401_cooldown_s: float = _SAAS_401_COOLDOWN_S_DEFAULT, transport: httpx.AsyncBaseTransport | None = None, timeout: float | None = None, logger: SdkLogger | None = None): ...
    async def aclose(self) -> None: ...
    async def __aenter__(self) -> "AsyncOAuthClientCredentialsAuthProvider": ...
    async def __aexit__(self, *args: Any, **kwargs: Any) -> None: ...
    def _token_cache_file(self) -> Path | None: ...
    def _tarpit_file(self) -> Path | None: ...
    def _now(self) -> float: ...
    def _is_valid(self, token: _OAuthToken) -> bool: ...
    def _try_load_file_cached_token(self) -> _OAuthToken | None: ...
    def _try_save_file_cached_token(self, token: _OAuthToken) -> None: ...
    def _is_tarpitted(self) -> bool: ...
    def _create_tarpit_file(self, reason: str) -> None: ...
    async def _fetch_token(self) -> _OAuthToken: ...
    async def aget_headers(self) -> Mapping[str, str]: ...
    def get_headers(self) -> Mapping[str, str]: ...
def inject_auth_event_hooks(httpx_args: dict[str, Any] | None, auth_provider: object, async_client: bool = False, log_level: str | None = None, logger: SdkLogger | None = None) -> dict[str, Any]: ...
