from __future__ import annotations

from typing import Literal, Protocol, TypedDict
from .logging import SdkLogger
BackpressureSeverity = Literal["healthy", "soft", "severe"]
BackpressureProfile = Literal["BALANCED", "LEGACY"]
class BackpressureState(TypedDict):
    severity: BackpressureSeverity
    consecutive: int
    permits_max: int | None
    permits_current: int
    waiters: int
    backoff_ms: int
class _Clock(Protocol):
    def time(self) -> float: ...
EXEMPT_METHODS: frozenset[str] = frozenset(
    {
        "complete_job",
        "fail_job",
        "throw_job_error",
        "complete_user_task",
    }
)
_INITIAL_MAX: int = 16
_FLOOR: int = 1
_SOFT_FACTOR: float = 0.70
_SEVERE_FACTOR: float = 0.50
_RECOVERY_INTERVAL_S: float = 1.0
_RECOVERY_STEP: int = 1
_SEVERE_THRESHOLD: int = 3
_DECAY_QUIET_S: float = 2.0
_MAX_WAITERS: int = 1000
_HEALTHY_RECOVERY_MULTIPLIER: float = 1.5
_UNLIMITED_AFTER_HEALTHY_S: float = 30.0
_BACKOFF_INITIAL_S: float = 0.025
_BACKOFF_MAX_S: float = 2.0
_BACKOFF_ESCALATE: float = 2.0
class BackpressureQueueFull(Exception):
    ...
def is_backpressure_response(status_code: int, body: str | None = None) -> bool: ...
def is_backpressure_error(exc: Exception) -> bool: ...
class BackpressureManager:
    def __init__(self, *, profile: BackpressureProfile = "BALANCED", logger: SdkLogger | None = None, clock: _Clock | None = None) -> None: ...
    @property
    def severity(self) -> BackpressureSeverity: ...
    def get_state(self) -> BackpressureState: ...
    def acquire(self) -> None: ...
    def release(self) -> None: ...
    def record_backpressure(self) -> None: ...
    def record_healthy_hint(self) -> None: ...
    def _scale_permits(self, factor: float) -> None: ...
    def _maybe_recover(self, now: float) -> None: ...
    def _log_severity(self, prev: str, curr: str) -> None: ...
    def _log_debug(self, event: str, data: dict[str, object]) -> None: ...
class AsyncBackpressureManager:
    def __init__(self, *, profile: BackpressureProfile = "BALANCED", logger: SdkLogger | None = None, clock: _Clock | None = None) -> None: ...
    @property
    def severity(self) -> BackpressureSeverity: ...
    def get_state(self) -> BackpressureState: ...
    async def acquire(self) -> None: ...
    async def release(self) -> None: ...
    async def record_backpressure(self) -> None: ...
    async def record_healthy_hint(self) -> None: ...
    def _scale_permits(self, factor: float) -> None: ...
    def _maybe_recover(self, now: float) -> None: ...
    def _log_severity(self, prev: str, curr: str) -> None: ...
    def _log_debug(self, event: str, data: dict[str, object]) -> None: ...
