from __future__ import annotations

from collections.abc import Callable
from typing import Protocol, runtime_checkable

__all__ = ["Clock", "LiveClock", "live_clock"]

@runtime_checkable
class Clock(Protocol):
    def now(self) -> float: ...
    async def sleep(self, seconds: float) -> None: ...
    def sleep_sync(self, seconds: float) -> None: ...

_SLEW_DIVISOR = 16.0

class LiveClock:
    def __init__(self, source: Callable[[], float] | None = None) -> None: ...
    def now(self) -> float: ...
    async def sleep(self, seconds: float) -> None: ...
    def sleep_sync(self, seconds: float) -> None: ...

live_clock: Clock = LiveClock()
