from __future__ import annotations

import asyncio
from collections.abc import Awaitable, Callable, Coroutine
from typing import Protocol, runtime_checkable
from camunda_orchestration_sdk.models.clock_pin_request import ClockPinRequest

__all__ = [
    "Clock",
    "EngineClock",
    "EngineClockTarget",
    "LiveClock",
    "ManualClock",
    "live_clock",
]

@runtime_checkable
class Clock(Protocol):
    def now(self) -> float: ...
    async def sleep(self, seconds: float) -> None: ...
    def sleep_sync(self, seconds: float) -> None: ...

_SLEW_DIVISOR = 16.0

class LiveClock:
    def __init__(self, source: Callable[[], float] | None = None) -> None: ...
    def now(self) -> float: ...
    async def sleep(self, seconds: float) -> None: ...
    def sleep_sync(self, seconds: float) -> None: ...

live_clock: Clock = LiveClock()

class ManualClock:
    def __init__(self, *, start: float = 0.0, auto_advance: bool = True) -> None: ...
    def now(self) -> float: ...
    async def sleep(self, seconds: float) -> None: ...
    def sleep_sync(self, seconds: float) -> None: ...
    async def advance(self, seconds: float) -> None: ...
    def advance_sync(self, seconds: float) -> None: ...
    def _settle_to(self, when: float) -> None: ...
    def _register(self, seconds: float) -> float: ...
    @property
    def sleeps(self) -> tuple[float, ...]: ...
    @property
    def now_calls(self) -> int: ...
    @property
    def pending(self) -> int: ...

@runtime_checkable
class EngineClockTarget(Protocol):
    def pin_clock(self, *, data: ClockPinRequest) -> Awaitable[None] | None: ...
    def reset_clock(self) -> Awaitable[None] | None: ...

class EngineClock:
    def __init__(
        self,
        target: EngineClockTarget,
        *,
        start: float | None = None,
        is_async: bool | None = None,
    ) -> None: ...
    def now(self) -> float: ...
    async def sleep(self, seconds: float) -> None: ...
    def sleep_sync(self, seconds: float) -> None: ...
    async def pin(self, at: float | None = None) -> None: ...
    def pin_sync(self, at: float | None = None) -> None: ...
    async def reset(self) -> None: ...
    def reset_sync(self) -> None: ...
    def _acquire_async(self) -> asyncio.Lock: ...
    def _bridge(self, coro: Coroutine[object, object, None], what: str) -> None: ...
    def _wake_instant(self, seconds: float) -> float: ...
    def _publish(self, at: float) -> None: ...
    def _unpin(self) -> None: ...
    def _require_async(self, what: str) -> None: ...
    @staticmethod
    def _current_owner() -> object: ...
    def _guard_reentry(self) -> None: ...
    async def _pin_async(self, at: float) -> None: ...
    def _pin_sync(self, at: float) -> None: ...
    @staticmethod
    async def _call(result: Awaitable[None] | None) -> None: ...

def _pin_request(at: float) -> ClockPinRequest: ...
