from __future__ import annotations

from collections.abc import Callable
from typing import Protocol, runtime_checkable

__all__ = ["Clock", "LiveClock", "ManualClock", "live_clock"]

@runtime_checkable
class Clock(Protocol):
    def now(self) -> float: ...
    async def sleep(self, seconds: float) -> None: ...
    def sleep_sync(self, seconds: float) -> None: ...

_SLEW_DIVISOR = 16.0

class LiveClock:
    def __init__(self, source: Callable[[], float] | None = None) -> None: ...
    def now(self) -> float: ...
    async def sleep(self, seconds: float) -> None: ...
    def sleep_sync(self, seconds: float) -> None: ...

live_clock: Clock = LiveClock()

class ManualClock:
    def __init__(self, *, start: float = 0.0, auto_advance: bool = True) -> None: ...
    def now(self) -> float: ...
    async def sleep(self, seconds: float) -> None: ...
    def sleep_sync(self, seconds: float) -> None: ...
    async def advance(self, seconds: float) -> None: ...
    def advance_sync(self, seconds: float) -> None: ...
    def _settle_to(self, when: float) -> None: ...
    def _register(self, seconds: float) -> float: ...
    @property
    def sleeps(self) -> tuple[float, ...]: ...
    @property
    def now_calls(self) -> int: ...
    @property
    def pending(self) -> int: ...
