from __future__ import annotations

from typing import Any, Protocol, runtime_checkable
@runtime_checkable
class CamundaLogger(Protocol):
    def debug(self, msg: str, *args: Any, **kwargs: Any) -> None: ...
    def info(self, msg: str, *args: Any, **kwargs: Any) -> None: ...
    def warning(self, msg: str, *args: Any, **kwargs: Any) -> None: ...
    def error(self, msg: str, *args: Any, **kwargs: Any) -> None: ...
class NullLogger:
    def debug(self, msg: str, *args: Any, **kwargs: Any) -> None: ...
    def info(self, msg: str, *args: Any, **kwargs: Any) -> None: ...
    def warning(self, msg: str, *args: Any, **kwargs: Any) -> None: ...
    def error(self, msg: str, *args: Any, **kwargs: Any) -> None: ...
    def trace(self, msg: str, *args: Any, **kwargs: Any) -> None: ...
def _get_default_logger() -> CamundaLogger: ...
class SdkLogger:
    def __init__(self, logger: CamundaLogger, prefix: str = "") -> None: ...
    def _fmt(self, msg: str) -> str: ...
    def debug(self, msg: str) -> None: ...
    def info(self, msg: str) -> None: ...
    def warning(self, msg: str) -> None: ...
    def error(self, msg: str) -> None: ...
    def trace(self, msg: str) -> None: ...
    def bind(self, **kwargs: str) -> SdkLogger: ...
    def __reduce__(self) -> tuple[type[SdkLogger], tuple[NullLogger]]: ...
def create_logger(logger: CamundaLogger | None = None) -> SdkLogger: ...
