from __future__ import annotations

import ssl
from pathlib import Path
from .configuration_resolver import CamundaSdkConfiguration
def build_ssl_context(config: CamundaSdkConfiguration) -> ssl.SSLContext | None: ...
def _read_path(path: str | None) -> str | None: ...
def _load_cert_chain(ctx: ssl.SSLContext, cert_pem: str, key_pem: str, passphrase: str | None) -> None: ...
def _write_temp_pem(pem: str) -> Path: ...
