from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.create_document_data import CreateDocumentData
from ...models.document_reference import DocumentReference
from ...models.problem_detail import ProblemDetail
from ...types import UNSET, Response, Unset
def _get_kwargs(body: CreateDocumentData, store_id: str | Unset = UNSET, document_id: str | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> DocumentReference | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[DocumentReference | ProblemDetail]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: CreateDocumentData, store_id: str | Unset = UNSET, document_id: str | Unset = UNSET) -> Response[DocumentReference | ProblemDetail]: ...
def sync(client: AuthenticatedClient | Client, body: CreateDocumentData, store_id: str | Unset = UNSET, document_id: str | Unset = UNSET, **kwargs: Any) -> DocumentReference: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: CreateDocumentData, store_id: str | Unset = UNSET, document_id: str | Unset = UNSET) -> Response[DocumentReference | ProblemDetail]: ...
async def asyncio(client: AuthenticatedClient | Client, body: CreateDocumentData, store_id: str | Unset = UNSET, document_id: str | Unset = UNSET, **kwargs: Any) -> DocumentReference: ...
