from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.create_deployment_data import CreateDeploymentData
from ...models.deployment_result import DeploymentResult
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(*, body: CreateDeploymentData) -> dict[str, Any]: ...
def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> DeploymentResult | ProblemDetail | None: ...
def _build_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Response[DeploymentResult | ProblemDetail]: ...
def sync_detailed(*, client: AuthenticatedClient, body: CreateDeploymentData) -> Response[DeploymentResult | ProblemDetail]: ...
def sync(*, client: AuthenticatedClient, body: CreateDeploymentData, **kwargs: Any) -> DeploymentResult: ...
async def asyncio_detailed(*, client: AuthenticatedClient, body: CreateDeploymentData) -> Response[DeploymentResult | ProblemDetail]: ...
async def asyncio(*, client: AuthenticatedClient, body: CreateDeploymentData, **kwargs: Any) -> DeploymentResult: ...
