from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.create_deployment_data import CreateDeploymentData
from ...models.create_deployment_response_200 import CreateDeploymentResponse200
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(body: CreateDeploymentData) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> CreateDeploymentResponse200 | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[CreateDeploymentResponse200 | ProblemDetail]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: CreateDeploymentData) -> Response[CreateDeploymentResponse200 | ProblemDetail]: ...
def sync(client: AuthenticatedClient | Client, body: CreateDeploymentData, **kwargs: Any) -> CreateDeploymentResponse200: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: CreateDeploymentData) -> Response[CreateDeploymentResponse200 | ProblemDetail]: ...
async def asyncio(client: AuthenticatedClient | Client, body: CreateDeploymentData, **kwargs: Any) -> CreateDeploymentResponse200: ...
