from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.delete_resource_request_type_0 import DeleteResourceRequestType0
from ...models.delete_resource_response import DeleteResourceResponse
from ...models.problem_detail import ProblemDetail
from ...types import UNSET, Response, Unset
def _get_kwargs(resource_key: str, body: DeleteResourceRequestType0 | None | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> DeleteResourceResponse | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[DeleteResourceResponse | ProblemDetail]: ...
def sync_detailed(resource_key: str, client: AuthenticatedClient | Client, body: DeleteResourceRequestType0 | None | Unset = UNSET) -> Response[DeleteResourceResponse | ProblemDetail]: ...
def sync(resource_key: str, client: AuthenticatedClient | Client, body: DeleteResourceRequestType0 | None | Unset = UNSET, **kwargs: Any) -> DeleteResourceResponse: ...
async def asyncio_detailed(resource_key: str, client: AuthenticatedClient | Client, body: DeleteResourceRequestType0 | None | Unset = UNSET) -> Response[DeleteResourceResponse | ProblemDetail]: ...
async def asyncio(resource_key: str, client: AuthenticatedClient | Client, body: DeleteResourceRequestType0 | None | Unset = UNSET, **kwargs: Any) -> DeleteResourceResponse: ...
