from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.get_resource_content_response_200 import GetResourceContentResponse200
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(resource_key: str) -> dict[str, Any]: ...
def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> GetResourceContentResponse200 | ProblemDetail | None: ...
def _build_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Response[GetResourceContentResponse200 | ProblemDetail]: ...
def sync_detailed(resource_key: str, *, client: AuthenticatedClient) -> Response[GetResourceContentResponse200 | ProblemDetail]: ...
def sync(resource_key: str, *, client: AuthenticatedClient, **kwargs: Any) -> GetResourceContentResponse200: ...
async def asyncio_detailed(resource_key: str, *, client: AuthenticatedClient) -> Response[GetResourceContentResponse200 | ProblemDetail]: ...
async def asyncio(resource_key: str, *, client: AuthenticatedClient, **kwargs: Any) -> GetResourceContentResponse200: ...
