from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.problem_detail import ProblemDetail
from ...types import File, Response
def _get_kwargs(resource_key: str) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> File | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[File | ProblemDetail]: ...
def sync_detailed(resource_key: str, client: AuthenticatedClient | Client) -> Response[File | ProblemDetail]: ...
def sync(resource_key: str, client: AuthenticatedClient | Client, **kwargs: Any) -> File: ...
async def asyncio_detailed(resource_key: str, client: AuthenticatedClient | Client) -> Response[File | ProblemDetail]: ...
async def asyncio(resource_key: str, client: AuthenticatedClient | Client, **kwargs: Any) -> File: ...
