from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.problem_detail import ProblemDetail
from ...models.set_variable_request import SetVariableRequest
from ...types import Response
def _get_kwargs(element_instance_key: str, body: SetVariableRequest) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Any | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[Any | ProblemDetail]: ...
def sync_detailed(element_instance_key: str, client: AuthenticatedClient | Client, body: SetVariableRequest) -> Response[Any | ProblemDetail]: ...
def sync(element_instance_key: str, client: AuthenticatedClient | Client, body: SetVariableRequest, **kwargs: Any) -> None: ...
async def asyncio_detailed(element_instance_key: str, client: AuthenticatedClient | Client, body: SetVariableRequest) -> Response[Any | ProblemDetail]: ...
async def asyncio(element_instance_key: str, client: AuthenticatedClient | Client, body: SetVariableRequest, **kwargs: Any) -> None: ...
