from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.element_instance_result import ElementInstanceResult
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(element_instance_key: str) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ElementInstanceResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ElementInstanceResult | ProblemDetail]: ...
def sync_detailed(element_instance_key: str, client: AuthenticatedClient | Client) -> Response[ElementInstanceResult | ProblemDetail]: ...
def sync(element_instance_key: str, client: AuthenticatedClient | Client, **kwargs: Any) -> ElementInstanceResult: ...
async def asyncio_detailed(element_instance_key: str, client: AuthenticatedClient | Client) -> Response[ElementInstanceResult | ProblemDetail]: ...
async def asyncio(element_instance_key: str, client: AuthenticatedClient | Client, **kwargs: Any) -> ElementInstanceResult: ...
