from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.element_instance_search_query import ElementInstanceSearchQuery
from ...models.element_instance_search_query_result import ElementInstanceSearchQueryResult
from ...models.problem_detail import ProblemDetail
from ...types import UNSET, Response, Unset
def _get_kwargs(body: ElementInstanceSearchQuery | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ElementInstanceSearchQueryResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ElementInstanceSearchQueryResult | ProblemDetail]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: ElementInstanceSearchQuery | Unset = UNSET) -> Response[ElementInstanceSearchQueryResult | ProblemDetail]: ...
def sync(client: AuthenticatedClient | Client, body: ElementInstanceSearchQuery | Unset = UNSET, **kwargs: Any) -> ElementInstanceSearchQueryResult: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: ElementInstanceSearchQuery | Unset = UNSET) -> Response[ElementInstanceSearchQueryResult | ProblemDetail]: ...
async def asyncio(client: AuthenticatedClient | Client, body: ElementInstanceSearchQuery | Unset = UNSET, **kwargs: Any) -> ElementInstanceSearchQueryResult: ...
