from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.batch_operation_search_query import BatchOperationSearchQuery
from ...models.batch_operation_search_query_result import BatchOperationSearchQueryResult
from ...models.problem_detail import ProblemDetail
from ...types import UNSET, Response, Unset
def _get_kwargs(body: BatchOperationSearchQuery | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> BatchOperationSearchQueryResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[BatchOperationSearchQueryResult | ProblemDetail]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: BatchOperationSearchQuery | Unset = UNSET) -> Response[BatchOperationSearchQueryResult | ProblemDetail]: ...
def sync(client: AuthenticatedClient | Client, body: BatchOperationSearchQuery | Unset = UNSET, **kwargs: Any) -> BatchOperationSearchQueryResult: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: BatchOperationSearchQuery | Unset = UNSET) -> Response[BatchOperationSearchQueryResult | ProblemDetail]: ...
async def asyncio(client: AuthenticatedClient | Client, body: BatchOperationSearchQuery | Unset = UNSET, **kwargs: Any) -> BatchOperationSearchQueryResult: ...
