from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.batch_operation_item_search_query_result import BatchOperationItemSearchQueryResult
from ...models.problem_detail import ProblemDetail
from ...models.search_batch_operation_items_data import SearchBatchOperationItemsData
from ...types import UNSET, Response, Unset
def _get_kwargs(body: SearchBatchOperationItemsData | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> BatchOperationItemSearchQueryResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[BatchOperationItemSearchQueryResult | ProblemDetail]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: SearchBatchOperationItemsData | Unset = UNSET) -> Response[BatchOperationItemSearchQueryResult | ProblemDetail]: ...
def sync(client: AuthenticatedClient | Client, body: SearchBatchOperationItemsData | Unset = UNSET, **kwargs: Any) -> BatchOperationItemSearchQueryResult: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: SearchBatchOperationItemsData | Unset = UNSET) -> Response[BatchOperationItemSearchQueryResult | ProblemDetail]: ...
async def asyncio(client: AuthenticatedClient | Client, body: SearchBatchOperationItemsData | Unset = UNSET, **kwargs: Any) -> BatchOperationItemSearchQueryResult: ...
