from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.problem_detail import ProblemDetail
from ...models.user_create_result import UserCreateResult
from ...models.user_request import UserRequest
from ...types import Response
def _get_kwargs(body: UserRequest) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ProblemDetail | UserCreateResult | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ProblemDetail | UserCreateResult]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: UserRequest) -> Response[ProblemDetail | UserCreateResult]: ...
def sync(client: AuthenticatedClient | Client, body: UserRequest, **kwargs: Any) -> UserCreateResult: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: UserRequest) -> Response[ProblemDetail | UserCreateResult]: ...
async def asyncio(client: AuthenticatedClient | Client, body: UserRequest, **kwargs: Any) -> UserCreateResult: ...
