from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.get_user_response_200 import GetUserResponse200
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(username: str) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> GetUserResponse200 | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[GetUserResponse200 | ProblemDetail]: ...
def sync_detailed(username: str, client: AuthenticatedClient | Client) -> Response[GetUserResponse200 | ProblemDetail]: ...
def sync(username: str, client: AuthenticatedClient | Client, **kwargs: Any) -> GetUserResponse200: ...
async def asyncio_detailed(username: str, client: AuthenticatedClient | Client) -> Response[GetUserResponse200 | ProblemDetail]: ...
async def asyncio(username: str, client: AuthenticatedClient | Client, **kwargs: Any) -> GetUserResponse200: ...
