from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.problem_detail import ProblemDetail
from ...models.user_result import UserResult
from ...types import Response
def _get_kwargs(username: str) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ProblemDetail | UserResult | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ProblemDetail | UserResult]: ...
def sync_detailed(username: str, client: AuthenticatedClient | Client) -> Response[ProblemDetail | UserResult]: ...
def sync(username: str, client: AuthenticatedClient | Client, **kwargs: Any) -> UserResult: ...
async def asyncio_detailed(username: str, client: AuthenticatedClient | Client) -> Response[ProblemDetail | UserResult]: ...
async def asyncio(username: str, client: AuthenticatedClient | Client, **kwargs: Any) -> UserResult: ...
