from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.problem_detail import ProblemDetail
from ...models.search_users_response_200 import SearchUsersResponse200
from ...models.user_search_query_request import UserSearchQueryRequest
from ...types import UNSET, Response, Unset
def _get_kwargs(body: UserSearchQueryRequest | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ProblemDetail | SearchUsersResponse200 | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ProblemDetail | SearchUsersResponse200]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: UserSearchQueryRequest | Unset = UNSET) -> Response[ProblemDetail | SearchUsersResponse200]: ...
def sync(client: AuthenticatedClient | Client, body: UserSearchQueryRequest | Unset = UNSET, **kwargs: Any) -> SearchUsersResponse200: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: UserSearchQueryRequest | Unset = UNSET) -> Response[ProblemDetail | SearchUsersResponse200]: ...
async def asyncio(client: AuthenticatedClient | Client, body: UserSearchQueryRequest | Unset = UNSET, **kwargs: Any) -> SearchUsersResponse200: ...
