from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.problem_detail import ProblemDetail
from ...models.user_update_request import UserUpdateRequest
from ...models.user_update_result import UserUpdateResult
from ...types import Response
def _get_kwargs(username: str, *, body: UserUpdateRequest) -> dict[str, Any]: ...
def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> ProblemDetail | UserUpdateResult | None: ...
def _build_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ProblemDetail | UserUpdateResult]: ...
def sync_detailed(username: str, *, client: AuthenticatedClient | Client, body: UserUpdateRequest) -> Response[ProblemDetail | UserUpdateResult]: ...
def sync(username: str, *, client: AuthenticatedClient | Client, body: UserUpdateRequest, **kwargs: Any) -> UserUpdateResult: ...
async def asyncio_detailed(username: str, *, client: AuthenticatedClient | Client, body: UserUpdateRequest) -> Response[ProblemDetail | UserUpdateResult]: ...
async def asyncio(username: str, *, client: AuthenticatedClient | Client, body: UserUpdateRequest, **kwargs: Any) -> UserUpdateResult: ...
