from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.get_user_task_form_response_200 import GetUserTaskFormResponse200
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(user_task_key: str) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Any | GetUserTaskFormResponse200 | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[Any | GetUserTaskFormResponse200 | ProblemDetail]: ...
def sync_detailed(user_task_key: str, client: AuthenticatedClient | Client) -> Response[Any | GetUserTaskFormResponse200 | ProblemDetail]: ...
def sync(user_task_key: str, client: AuthenticatedClient | Client, **kwargs: Any) -> GetUserTaskFormResponse200: ...
async def asyncio_detailed(user_task_key: str, client: AuthenticatedClient | Client) -> Response[Any | GetUserTaskFormResponse200 | ProblemDetail]: ...
async def asyncio(user_task_key: str, client: AuthenticatedClient | Client, **kwargs: Any) -> GetUserTaskFormResponse200: ...
