from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.form_result import FormResult
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(user_task_key: str) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Any | FormResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[Any | FormResult | ProblemDetail]: ...
def sync_detailed(user_task_key: str, client: AuthenticatedClient | Client) -> Response[Any | FormResult | ProblemDetail]: ...
def sync(user_task_key: str, client: AuthenticatedClient | Client, **kwargs: Any) -> FormResult: ...
async def asyncio_detailed(user_task_key: str, client: AuthenticatedClient | Client) -> Response[Any | FormResult | ProblemDetail]: ...
async def asyncio(user_task_key: str, client: AuthenticatedClient | Client, **kwargs: Any) -> FormResult: ...
