from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.problem_detail import ProblemDetail
from ...models.user_task_result import UserTaskResult
from ...types import Response
def _get_kwargs(user_task_key: str) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ProblemDetail | UserTaskResult | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ProblemDetail | UserTaskResult]: ...
def sync_detailed(user_task_key: str, client: AuthenticatedClient | Client) -> Response[ProblemDetail | UserTaskResult]: ...
def sync(user_task_key: str, client: AuthenticatedClient | Client, **kwargs: Any) -> UserTaskResult: ...
async def asyncio_detailed(user_task_key: str, client: AuthenticatedClient | Client) -> Response[ProblemDetail | UserTaskResult]: ...
async def asyncio(user_task_key: str, client: AuthenticatedClient | Client, **kwargs: Any) -> UserTaskResult: ...
