from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.problem_detail import ProblemDetail
from ...models.user_task_search_query import UserTaskSearchQuery
from ...models.user_task_search_query_result import UserTaskSearchQueryResult
from ...types import UNSET, Response, Unset
def _get_kwargs(body: UserTaskSearchQuery | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ProblemDetail | UserTaskSearchQueryResult | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ProblemDetail | UserTaskSearchQueryResult]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: UserTaskSearchQuery | Unset = UNSET) -> Response[ProblemDetail | UserTaskSearchQueryResult]: ...
def sync(client: AuthenticatedClient | Client, body: UserTaskSearchQuery | Unset = UNSET, **kwargs: Any) -> UserTaskSearchQueryResult: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: UserTaskSearchQuery | Unset = UNSET) -> Response[ProblemDetail | UserTaskSearchQueryResult]: ...
async def asyncio(client: AuthenticatedClient | Client, body: UserTaskSearchQuery | Unset = UNSET, **kwargs: Any) -> UserTaskSearchQueryResult: ...
