from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.audit_log_search_query_result import AuditLogSearchQueryResult
from ...models.problem_detail import ProblemDetail
from ...models.user_task_audit_log_search_query_request import UserTaskAuditLogSearchQueryRequest
from ...types import UNSET, Response, Unset
def _get_kwargs(user_task_key: str, body: UserTaskAuditLogSearchQueryRequest | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> AuditLogSearchQueryResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[AuditLogSearchQueryResult | ProblemDetail]: ...
def sync_detailed(user_task_key: str, client: AuthenticatedClient | Client, body: UserTaskAuditLogSearchQueryRequest | Unset = UNSET) -> Response[AuditLogSearchQueryResult | ProblemDetail]: ...
def sync(user_task_key: str, client: AuthenticatedClient | Client, body: UserTaskAuditLogSearchQueryRequest | Unset = UNSET, **kwargs: Any) -> AuditLogSearchQueryResult: ...
async def asyncio_detailed(user_task_key: str, client: AuthenticatedClient | Client, body: UserTaskAuditLogSearchQueryRequest | Unset = UNSET) -> Response[AuditLogSearchQueryResult | ProblemDetail]: ...
async def asyncio(user_task_key: str, client: AuthenticatedClient | Client, body: UserTaskAuditLogSearchQueryRequest | Unset = UNSET, **kwargs: Any) -> AuditLogSearchQueryResult: ...
