from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.camunda_user_result import CamundaUserResult
from ...models.problem_detail import ProblemDetail
from ...types import Response

def _get_kwargs() -> dict[str, Any]: ...
def _parse_response(
    client: AuthenticatedClient | Client, response: httpx.Response
) -> CamundaUserResult | ProblemDetail | None: ...
def _build_response(
    client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[CamundaUserResult | ProblemDetail]: ...
def sync_detailed(
    client: AuthenticatedClient,
) -> Response[CamundaUserResult | ProblemDetail]: ...
def sync(client: AuthenticatedClient, **kwargs: Any) -> CamundaUserResult: ...
async def asyncio_detailed(
    client: AuthenticatedClient,
) -> Response[CamundaUserResult | ProblemDetail]: ...
async def asyncio(client: AuthenticatedClient, **kwargs: Any) -> CamundaUserResult: ...
