from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.problem_detail import ProblemDetail
from ...models.process_definition_element_statistics_query import ProcessDefinitionElementStatisticsQuery
from ...models.process_definition_element_statistics_query_result import ProcessDefinitionElementStatisticsQueryResult
from ...types import UNSET, Response, Unset
def _get_kwargs(process_definition_key: str, body: ProcessDefinitionElementStatisticsQuery | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ProblemDetail | ProcessDefinitionElementStatisticsQueryResult | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ProblemDetail | ProcessDefinitionElementStatisticsQueryResult]: ...
def sync_detailed(process_definition_key: str, client: AuthenticatedClient | Client, body: ProcessDefinitionElementStatisticsQuery | Unset = UNSET) -> Response[ProblemDetail | ProcessDefinitionElementStatisticsQueryResult]: ...
def sync(process_definition_key: str, client: AuthenticatedClient | Client, body: ProcessDefinitionElementStatisticsQuery | Unset = UNSET, **kwargs: Any) -> ProcessDefinitionElementStatisticsQueryResult: ...
async def asyncio_detailed(process_definition_key: str, client: AuthenticatedClient | Client, body: ProcessDefinitionElementStatisticsQuery | Unset = UNSET) -> Response[ProblemDetail | ProcessDefinitionElementStatisticsQueryResult]: ...
async def asyncio(process_definition_key: str, client: AuthenticatedClient | Client, body: ProcessDefinitionElementStatisticsQuery | Unset = UNSET, **kwargs: Any) -> ProcessDefinitionElementStatisticsQueryResult: ...
