from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.problem_detail import ProblemDetail
from ...models.system_configuration_response import SystemConfigurationResponse
from ...types import Response
def _get_kwargs() -> dict[str, Any]: ...
def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> ProblemDetail | SystemConfigurationResponse | None: ...
def _build_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ProblemDetail | SystemConfigurationResponse]: ...
def sync_detailed(*, client: AuthenticatedClient | Client) -> Response[ProblemDetail | SystemConfigurationResponse]: ...
def sync(*, client: AuthenticatedClient | Client, **kwargs: Any) -> SystemConfigurationResponse: ...
async def asyncio_detailed(*, client: AuthenticatedClient | Client) -> Response[ProblemDetail | SystemConfigurationResponse]: ...
async def asyncio(*, client: AuthenticatedClient | Client, **kwargs: Any) -> SystemConfigurationResponse: ...
