from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.activate_jobs_response_200 import ActivateJobsResponse200
from ...models.job_activation_request import JobActivationRequest
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(body: JobActivationRequest) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ActivateJobsResponse200 | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ActivateJobsResponse200 | ProblemDetail]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: JobActivationRequest) -> Response[ActivateJobsResponse200 | ProblemDetail]: ...
def sync(client: AuthenticatedClient | Client, body: JobActivationRequest, **kwargs: Any) -> ActivateJobsResponse200: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: JobActivationRequest) -> Response[ActivateJobsResponse200 | ProblemDetail]: ...
async def asyncio(client: AuthenticatedClient | Client, body: JobActivationRequest, **kwargs: Any) -> ActivateJobsResponse200: ...
