from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.job_activation_request import JobActivationRequest
from ...models.job_activation_result import JobActivationResult
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(body: JobActivationRequest) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> JobActivationResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[JobActivationResult | ProblemDetail]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: JobActivationRequest) -> Response[JobActivationResult | ProblemDetail]: ...
def sync(client: AuthenticatedClient | Client, body: JobActivationRequest, **kwargs: Any) -> JobActivationResult: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: JobActivationRequest) -> Response[JobActivationResult | ProblemDetail]: ...
async def asyncio(client: AuthenticatedClient | Client, body: JobActivationRequest, **kwargs: Any) -> JobActivationResult: ...
