from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.job_type_statistics_query import JobTypeStatisticsQuery
from ...models.job_type_statistics_query_result import JobTypeStatisticsQueryResult
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(body: JobTypeStatisticsQuery) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> JobTypeStatisticsQueryResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[JobTypeStatisticsQueryResult | ProblemDetail]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: JobTypeStatisticsQuery) -> Response[JobTypeStatisticsQueryResult | ProblemDetail]: ...
def sync(client: AuthenticatedClient | Client, body: JobTypeStatisticsQuery, **kwargs: Any) -> JobTypeStatisticsQueryResult: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: JobTypeStatisticsQuery) -> Response[JobTypeStatisticsQueryResult | ProblemDetail]: ...
async def asyncio(client: AuthenticatedClient | Client, body: JobTypeStatisticsQuery, **kwargs: Any) -> JobTypeStatisticsQueryResult: ...
