from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.job_error_statistics_query import JobErrorStatisticsQuery
from ...models.job_error_statistics_query_result import JobErrorStatisticsQueryResult
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(*, body: JobErrorStatisticsQuery) -> dict[str, Any]: ...
def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> JobErrorStatisticsQueryResult | ProblemDetail | None: ...
def _build_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Response[JobErrorStatisticsQueryResult | ProblemDetail]: ...
def sync_detailed(*, client: AuthenticatedClient | Client, body: JobErrorStatisticsQuery) -> Response[JobErrorStatisticsQueryResult | ProblemDetail]: ...
def sync(*, client: AuthenticatedClient | Client, body: JobErrorStatisticsQuery, **kwargs: Any) -> JobErrorStatisticsQueryResult: ...
async def asyncio_detailed(*, client: AuthenticatedClient | Client, body: JobErrorStatisticsQuery) -> Response[JobErrorStatisticsQueryResult | ProblemDetail]: ...
async def asyncio(*, client: AuthenticatedClient | Client, body: JobErrorStatisticsQuery, **kwargs: Any) -> JobErrorStatisticsQueryResult: ...
