from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.job_time_series_statistics_query import JobTimeSeriesStatisticsQuery
from ...models.job_time_series_statistics_query_result import JobTimeSeriesStatisticsQueryResult
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(*, body: JobTimeSeriesStatisticsQuery) -> dict[str, Any]: ...
def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> JobTimeSeriesStatisticsQueryResult | ProblemDetail | None: ...
def _build_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Response[JobTimeSeriesStatisticsQueryResult | ProblemDetail]: ...
def sync_detailed(*, client: AuthenticatedClient | Client, body: JobTimeSeriesStatisticsQuery) -> Response[JobTimeSeriesStatisticsQueryResult | ProblemDetail]: ...
def sync(*, client: AuthenticatedClient | Client, body: JobTimeSeriesStatisticsQuery, **kwargs: Any) -> JobTimeSeriesStatisticsQueryResult: ...
async def asyncio_detailed(*, client: AuthenticatedClient | Client, body: JobTimeSeriesStatisticsQuery) -> Response[JobTimeSeriesStatisticsQueryResult | ProblemDetail]: ...
async def asyncio(*, client: AuthenticatedClient | Client, body: JobTimeSeriesStatisticsQuery, **kwargs: Any) -> JobTimeSeriesStatisticsQueryResult: ...
