from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.job_worker_statistics_query import JobWorkerStatisticsQuery
from ...models.job_worker_statistics_query_result import JobWorkerStatisticsQueryResult
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(*, body: JobWorkerStatisticsQuery) -> dict[str, Any]: ...
def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> JobWorkerStatisticsQueryResult | ProblemDetail | None: ...
def _build_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Response[JobWorkerStatisticsQueryResult | ProblemDetail]: ...
def sync_detailed(*, client: AuthenticatedClient | Client, body: JobWorkerStatisticsQuery) -> Response[JobWorkerStatisticsQueryResult | ProblemDetail]: ...
def sync(*, client: AuthenticatedClient | Client, body: JobWorkerStatisticsQuery, **kwargs: Any) -> JobWorkerStatisticsQueryResult: ...
async def asyncio_detailed(*, client: AuthenticatedClient | Client, body: JobWorkerStatisticsQuery) -> Response[JobWorkerStatisticsQueryResult | ProblemDetail]: ...
async def asyncio(*, client: AuthenticatedClient | Client, body: JobWorkerStatisticsQuery, **kwargs: Any) -> JobWorkerStatisticsQueryResult: ...
