from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.job_search_query import JobSearchQuery
from ...models.problem_detail import ProblemDetail
from ...models.search_jobs_response_200 import SearchJobsResponse200
from ...types import UNSET, Response, Unset
def _get_kwargs(body: JobSearchQuery | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ProblemDetail | SearchJobsResponse200 | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ProblemDetail | SearchJobsResponse200]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: JobSearchQuery | Unset = UNSET) -> Response[ProblemDetail | SearchJobsResponse200]: ...
def sync(client: AuthenticatedClient | Client, body: JobSearchQuery | Unset = UNSET, **kwargs: Any) -> SearchJobsResponse200: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: JobSearchQuery | Unset = UNSET) -> Response[ProblemDetail | SearchJobsResponse200]: ...
async def asyncio(client: AuthenticatedClient | Client, body: JobSearchQuery | Unset = UNSET, **kwargs: Any) -> SearchJobsResponse200: ...
