from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.job_search_query import JobSearchQuery
from ...models.job_search_query_result import JobSearchQueryResult
from ...models.problem_detail import ProblemDetail
from ...types import UNSET, Response, Unset
def _get_kwargs(body: JobSearchQuery | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> JobSearchQueryResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[JobSearchQueryResult | ProblemDetail]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: JobSearchQuery | Unset = UNSET) -> Response[JobSearchQueryResult | ProblemDetail]: ...
def sync(client: AuthenticatedClient | Client, body: JobSearchQuery | Unset = UNSET, **kwargs: Any) -> JobSearchQueryResult: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: JobSearchQuery | Unset = UNSET) -> Response[JobSearchQueryResult | ProblemDetail]: ...
async def asyncio(client: AuthenticatedClient | Client, body: JobSearchQuery | Unset = UNSET, **kwargs: Any) -> JobSearchQueryResult: ...
