from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.audit_log_result import AuditLogResult
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(audit_log_key: str) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> AuditLogResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[AuditLogResult | ProblemDetail]: ...
def sync_detailed(audit_log_key: str, client: AuthenticatedClient | Client) -> Response[AuditLogResult | ProblemDetail]: ...
def sync(audit_log_key: str, client: AuthenticatedClient | Client, **kwargs: Any) -> AuditLogResult: ...
async def asyncio_detailed(audit_log_key: str, client: AuthenticatedClient | Client) -> Response[AuditLogResult | ProblemDetail]: ...
async def asyncio(audit_log_key: str, client: AuthenticatedClient | Client, **kwargs: Any) -> AuditLogResult: ...
