from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.get_audit_log_response_200 import GetAuditLogResponse200
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(audit_log_key: str) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> GetAuditLogResponse200 | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[GetAuditLogResponse200 | ProblemDetail]: ...
def sync_detailed(audit_log_key: str, client: AuthenticatedClient | Client) -> Response[GetAuditLogResponse200 | ProblemDetail]: ...
def sync(audit_log_key: str, client: AuthenticatedClient | Client, **kwargs: Any) -> GetAuditLogResponse200: ...
async def asyncio_detailed(audit_log_key: str, client: AuthenticatedClient | Client) -> Response[GetAuditLogResponse200 | ProblemDetail]: ...
async def asyncio(audit_log_key: str, client: AuthenticatedClient | Client, **kwargs: Any) -> GetAuditLogResponse200: ...
