from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.audit_log_search_query_request import AuditLogSearchQueryRequest
from ...models.audit_log_search_query_result import AuditLogSearchQueryResult
from ...models.problem_detail import ProblemDetail
from ...types import UNSET, Response, Unset
def _get_kwargs(body: AuditLogSearchQueryRequest | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Any | AuditLogSearchQueryResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[Any | AuditLogSearchQueryResult | ProblemDetail]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: AuditLogSearchQueryRequest | Unset = UNSET) -> Response[Any | AuditLogSearchQueryResult | ProblemDetail]: ...
def sync(client: AuthenticatedClient | Client, body: AuditLogSearchQueryRequest | Unset = UNSET, **kwargs: Any) -> AuditLogSearchQueryResult: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: AuditLogSearchQueryRequest | Unset = UNSET) -> Response[Any | AuditLogSearchQueryResult | ProblemDetail]: ...
async def asyncio(client: AuthenticatedClient | Client, body: AuditLogSearchQueryRequest | Unset = UNSET, **kwargs: Any) -> AuditLogSearchQueryResult: ...
