from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.audit_log_search_query_request import AuditLogSearchQueryRequest
from ...models.problem_detail import ProblemDetail
from ...models.search_audit_logs_response_200 import SearchAuditLogsResponse200
from ...types import UNSET, Response, Unset
def _get_kwargs(body: AuditLogSearchQueryRequest | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Any | ProblemDetail | SearchAuditLogsResponse200 | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[Any | ProblemDetail | SearchAuditLogsResponse200]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: AuditLogSearchQueryRequest | Unset = UNSET) -> Response[Any | ProblemDetail | SearchAuditLogsResponse200]: ...
def sync(client: AuthenticatedClient | Client, body: AuditLogSearchQueryRequest | Unset = UNSET, **kwargs: Any) -> SearchAuditLogsResponse200: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: AuditLogSearchQueryRequest | Unset = UNSET) -> Response[Any | ProblemDetail | SearchAuditLogsResponse200]: ...
async def asyncio(client: AuthenticatedClient | Client, body: AuditLogSearchQueryRequest | Unset = UNSET, **kwargs: Any) -> SearchAuditLogsResponse200: ...
