from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.authorization_create_result import AuthorizationCreateResult
from ...models.authorization_id_based_request import AuthorizationIdBasedRequest
from ...models.authorization_property_based_request import AuthorizationPropertyBasedRequest
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(body: AuthorizationIdBasedRequest | AuthorizationPropertyBasedRequest) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> AuthorizationCreateResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[AuthorizationCreateResult | ProblemDetail]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: AuthorizationIdBasedRequest | AuthorizationPropertyBasedRequest) -> Response[AuthorizationCreateResult | ProblemDetail]: ...
def sync(client: AuthenticatedClient | Client, body: AuthorizationIdBasedRequest | AuthorizationPropertyBasedRequest, **kwargs: Any) -> AuthorizationCreateResult: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: AuthorizationIdBasedRequest | AuthorizationPropertyBasedRequest) -> Response[AuthorizationCreateResult | ProblemDetail]: ...
async def asyncio(client: AuthenticatedClient | Client, body: AuthorizationIdBasedRequest | AuthorizationPropertyBasedRequest, **kwargs: Any) -> AuthorizationCreateResult: ...
