from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.incident_resolution_request import IncidentResolutionRequest
from ...models.problem_detail import ProblemDetail
from ...types import UNSET, Response, Unset
def _get_kwargs(incident_key: str, body: IncidentResolutionRequest | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Any | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[Any | ProblemDetail]: ...
def sync_detailed(incident_key: str, client: AuthenticatedClient | Client, body: IncidentResolutionRequest | Unset = UNSET) -> Response[Any | ProblemDetail]: ...
def sync(incident_key: str, client: AuthenticatedClient | Client, body: IncidentResolutionRequest | Unset = UNSET, **kwargs: Any) -> None: ...
async def asyncio_detailed(incident_key: str, client: AuthenticatedClient | Client, body: IncidentResolutionRequest | Unset = UNSET) -> Response[Any | ProblemDetail]: ...
async def asyncio(incident_key: str, client: AuthenticatedClient | Client, body: IncidentResolutionRequest | Unset = UNSET, **kwargs: Any) -> None: ...
