from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.expression_evaluation_request import ExpressionEvaluationRequest
from ...models.expression_evaluation_result import ExpressionEvaluationResult
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(body: ExpressionEvaluationRequest) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ExpressionEvaluationResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ExpressionEvaluationResult | ProblemDetail]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: ExpressionEvaluationRequest) -> Response[ExpressionEvaluationResult | ProblemDetail]: ...
def sync(client: AuthenticatedClient | Client, body: ExpressionEvaluationRequest, **kwargs: Any) -> ExpressionEvaluationResult: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: ExpressionEvaluationRequest) -> Response[ExpressionEvaluationResult | ProblemDetail]: ...
async def asyncio(client: AuthenticatedClient | Client, body: ExpressionEvaluationRequest, **kwargs: Any) -> ExpressionEvaluationResult: ...
