from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.delete_decision_instance_data_type_0 import DeleteDecisionInstanceDataType0
from ...models.problem_detail import ProblemDetail
from ...types import UNSET, Response, Unset
def _get_kwargs(decision_instance_key: str, body: DeleteDecisionInstanceDataType0 | None | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Any | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[Any | ProblemDetail]: ...
def sync_detailed(decision_instance_key: str, client: AuthenticatedClient | Client, body: DeleteDecisionInstanceDataType0 | None | Unset = UNSET) -> Response[Any | ProblemDetail]: ...
def sync(decision_instance_key: str, client: AuthenticatedClient | Client, body: DeleteDecisionInstanceDataType0 | None | Unset = UNSET, **kwargs: Any) -> None: ...
async def asyncio_detailed(decision_instance_key: str, client: AuthenticatedClient | Client, body: DeleteDecisionInstanceDataType0 | None | Unset = UNSET) -> Response[Any | ProblemDetail]: ...
async def asyncio(decision_instance_key: str, client: AuthenticatedClient | Client, body: DeleteDecisionInstanceDataType0 | None | Unset = UNSET, **kwargs: Any) -> None: ...
