from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.decision_instance_get_query_result import DecisionInstanceGetQueryResult
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(decision_evaluation_instance_key: str) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> DecisionInstanceGetQueryResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[DecisionInstanceGetQueryResult | ProblemDetail]: ...
def sync_detailed(decision_evaluation_instance_key: str, client: AuthenticatedClient | Client) -> Response[DecisionInstanceGetQueryResult | ProblemDetail]: ...
def sync(decision_evaluation_instance_key: str, client: AuthenticatedClient | Client, **kwargs: Any) -> DecisionInstanceGetQueryResult: ...
async def asyncio_detailed(decision_evaluation_instance_key: str, client: AuthenticatedClient | Client) -> Response[DecisionInstanceGetQueryResult | ProblemDetail]: ...
async def asyncio(decision_evaluation_instance_key: str, client: AuthenticatedClient | Client, **kwargs: Any) -> DecisionInstanceGetQueryResult: ...
