from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.decision_instance_search_query import DecisionInstanceSearchQuery
from ...models.decision_instance_search_query_result import DecisionInstanceSearchQueryResult
from ...models.problem_detail import ProblemDetail
from ...types import UNSET, Response, Unset
def _get_kwargs(body: DecisionInstanceSearchQuery | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> DecisionInstanceSearchQueryResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[DecisionInstanceSearchQueryResult | ProblemDetail]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: DecisionInstanceSearchQuery | Unset = UNSET) -> Response[DecisionInstanceSearchQueryResult | ProblemDetail]: ...
def sync(client: AuthenticatedClient | Client, body: DecisionInstanceSearchQuery | Unset = UNSET, **kwargs: Any) -> DecisionInstanceSearchQueryResult: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: DecisionInstanceSearchQuery | Unset = UNSET) -> Response[DecisionInstanceSearchQueryResult | ProblemDetail]: ...
async def asyncio(client: AuthenticatedClient | Client, body: DecisionInstanceSearchQuery | Unset = UNSET, **kwargs: Any) -> DecisionInstanceSearchQueryResult: ...
