from enum import Enum
class AuthorizationPropertyBasedRequestPermissionTypesItem(str, Enum):
    ACCESS = "ACCESS"
    CANCEL_PROCESS_INSTANCE = "CANCEL_PROCESS_INSTANCE"
    CLAIM = "CLAIM"
    COMPLETE = "COMPLETE"
    CREATE = "CREATE"
    CREATE_BATCH_OPERATION_CANCEL_PROCESS_INSTANCE = (
            "CREATE_BATCH_OPERATION_CANCEL_PROCESS_INSTANCE"
        )
    CREATE_BATCH_OPERATION_DELETE_DECISION_DEFINITION = (
            "CREATE_BATCH_OPERATION_DELETE_DECISION_DEFINITION"
        )
    CREATE_BATCH_OPERATION_DELETE_DECISION_INSTANCE = (
            "CREATE_BATCH_OPERATION_DELETE_DECISION_INSTANCE"
        )
    CREATE_BATCH_OPERATION_DELETE_PROCESS_DEFINITION = (
            "CREATE_BATCH_OPERATION_DELETE_PROCESS_DEFINITION"
        )
    CREATE_BATCH_OPERATION_DELETE_PROCESS_INSTANCE = (
            "CREATE_BATCH_OPERATION_DELETE_PROCESS_INSTANCE"
        )
    CREATE_BATCH_OPERATION_MIGRATE_PROCESS_INSTANCE = (
            "CREATE_BATCH_OPERATION_MIGRATE_PROCESS_INSTANCE"
        )
    CREATE_BATCH_OPERATION_MODIFY_PROCESS_INSTANCE = (
            "CREATE_BATCH_OPERATION_MODIFY_PROCESS_INSTANCE"
        )
    CREATE_BATCH_OPERATION_RESOLVE_INCIDENT = "CREATE_BATCH_OPERATION_RESOLVE_INCIDENT"
    CREATE_DECISION_INSTANCE = "CREATE_DECISION_INSTANCE"
    CREATE_PROCESS_INSTANCE = "CREATE_PROCESS_INSTANCE"
    CREATE_TASK_LISTENER = "CREATE_TASK_LISTENER"
    DELETE = "DELETE"
    DELETE_DECISION_INSTANCE = "DELETE_DECISION_INSTANCE"
    DELETE_DRD = "DELETE_DRD"
    DELETE_FORM = "DELETE_FORM"
    DELETE_PROCESS = "DELETE_PROCESS"
    DELETE_PROCESS_INSTANCE = "DELETE_PROCESS_INSTANCE"
    DELETE_RESOURCE = "DELETE_RESOURCE"
    DELETE_TASK_LISTENER = "DELETE_TASK_LISTENER"
    EVALUATE = "EVALUATE"
    MODIFY_PROCESS_INSTANCE = "MODIFY_PROCESS_INSTANCE"
    READ = "READ"
    READ_DECISION_DEFINITION = "READ_DECISION_DEFINITION"
    READ_DECISION_INSTANCE = "READ_DECISION_INSTANCE"
    READ_JOB_METRIC = "READ_JOB_METRIC"
    READ_PROCESS_DEFINITION = "READ_PROCESS_DEFINITION"
    READ_PROCESS_INSTANCE = "READ_PROCESS_INSTANCE"
    READ_TASK_LISTENER = "READ_TASK_LISTENER"
    READ_USAGE_METRIC = "READ_USAGE_METRIC"
    READ_USER_TASK = "READ_USER_TASK"
    UPDATE = "UPDATE"
    UPDATE_PROCESS_INSTANCE = "UPDATE_PROCESS_INSTANCE"
    UPDATE_TASK_LISTENER = "UPDATE_TASK_LISTENER"
    UPDATE_USER_TASK = "UPDATE_USER_TASK"
    def __str__(self) -> str: ...
