from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.decision_requirements_result import DecisionRequirementsResult
from ...models.problem_detail import ProblemDetail
from ...types import Response
def _get_kwargs(decision_requirements_key: str) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> DecisionRequirementsResult | ProblemDetail | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[DecisionRequirementsResult | ProblemDetail]: ...
def sync_detailed(decision_requirements_key: str, client: AuthenticatedClient | Client) -> Response[DecisionRequirementsResult | ProblemDetail]: ...
def sync(decision_requirements_key: str, client: AuthenticatedClient | Client, **kwargs: Any) -> DecisionRequirementsResult: ...
async def asyncio_detailed(decision_requirements_key: str, client: AuthenticatedClient | Client) -> Response[DecisionRequirementsResult | ProblemDetail]: ...
async def asyncio(decision_requirements_key: str, client: AuthenticatedClient | Client, **kwargs: Any) -> DecisionRequirementsResult: ...
