"""Hook 0350 — dependent-presence couplings declared with ``x-present-when``.

OpenAPI 3.x cannot say a response field is present only when a request set a particular
flag, so the specification states it out of band: a field-level
``x-present-when: {request: <flag>, equals: true}`` marker on the conditional field
(upstream camunda/camunda#62777, applied to ``ActivatedJobResult.jobLeaseToken``).

This hook derives the couplings from the spec into
``camunda_orchestration_sdk/runtime/present_when_generated.py`` so the hand-written runtime
guard (``runtime/present_when.py``) enforces what the specification declares rather than a
relationship hardcoded from memory: if upstream renames the flag, moves the field, or adds
a second conditional field, the generated table changes and the guards in the acceptance
tests fail.

Runs after 0300 (which copies ``runtime/`` into the package) so the target directory exists.
Deliberately generic over the number of markers; generation fails if the table would come
out empty or a marker is malformed.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import yaml

HEADER = '''\
# @generated by hooks/post_gen/0350_generate_present_when.py — DO NOT EDIT.
#
# Dependent-presence couplings the specification declares with `x-present-when`:
# `response_schema.response_field` is present exactly when a request set `request_flag`.
# OpenAPI cannot express this, so the runtime carries it and `present_when.py` is the
# evidence it still matches the specification.

from __future__ import annotations

from typing import NamedTuple


class PresentWhenCoupling(NamedTuple):
    """A dependent-presence relationship declared by `x-present-when`."""

    response_schema: str
    response_field: str
    request_flag: str

'''


def _load_spec(path: Path) -> dict[str, Any] | None:
    with open(path, encoding="utf-8") as f:
        if path.suffix == ".json":
            return json.load(f)
        return yaml.safe_load(f)


def derive_couplings(schemas: dict[str, Any]) -> list[tuple[str, str, str]]:
    """Extract every ``x-present-when`` coupling as ``(schema, field, flag)``.

    Raises ``SystemExit`` on a malformed marker or an empty result, so a spec that meant to
    declare a coupling cannot silently produce an empty table.
    """
    couplings: list[tuple[str, str, str]] = []
    for schema_name in sorted(schemas):
        schema = schemas[schema_name]
        if not isinstance(schema, dict):
            continue
        props = schema.get("properties")
        if not isinstance(props, dict):
            continue
        for field_name in sorted(props):
            field = props[field_name]
            if not isinstance(field, dict):
                continue
            # Key presence, not truthiness: an explicit `x-present-when: null` is a
            # malformed marker, and `.get()` would let it masquerade as an absent one and
            # be skipped, so the runtime would drift from a spec that meant to declare a
            # coupling. Let it reach the validation below and fail loudly.
            if "x-present-when" not in field:
                continue
            marker = field["x-present-when"]
            request = marker.get("request") if isinstance(marker, dict) else None
            # `request` must be a non-empty string, not merely truthy: a numeric or object
            # request would otherwise reach the renderer and crash with an opaque error
            # instead of this explicit diagnostic.
            if (
                not isinstance(marker, dict)
                or not isinstance(request, str)
                or not request
                or marker.get("equals") is not True
            ):
                raise SystemExit(
                    f"hook 0350: x-present-when on {schema_name}.{field_name} is {marker!r}, "
                    "which is not the 'present when <flag> is true' shape the runtime guards "
                    "are built on. Teach this hook the new shape rather than dropping the marker."
                )
            couplings.append((schema_name, field_name, request))

    if not couplings:
        raise SystemExit(
            "hook 0350: the bundled spec declares no x-present-when markers. Either the "
            "bundler is stripping the vendor key or upstream removed it; emitting an empty "
            "table would silently retire the runtime guards built on it."
        )
    return couplings


def render(couplings: list[tuple[str, str, str]]) -> str:
    """Render the derived couplings as the generated Python module."""
    lines = [HEADER]
    lines.append("\n# Ordered by schema then field so the table is stable across regenerations.\n")
    lines.append("PRESENT_WHEN_COUPLINGS: tuple[PresentWhenCoupling, ...] = (\n")
    for schema_name, field_name, flag in couplings:
        lines.append(
            f"    PresentWhenCoupling({schema_name!r}, {field_name!r}, {flag!r}),\n"
        )
    lines.append(")\n")
    return "".join(lines)


def _snake(name: str) -> str:
    s1 = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", name)
    s2 = re.sub("([a-z0-9])([A-Z])", r"\1_\2", s1)
    return s2.replace("__", "_").lower()


def tolerate_absent_field(source: str, field: str) -> str:
    """Give a marker-declared field's ``d.pop`` a ``None`` default.

    ``x-present-when`` means the key is *absent* — not null — when the flag was not set, and
    an older server omits it regardless. The generator emits a bare ``d.pop("field")``, which
    raises ``KeyError`` on exactly those responses, so the whole activation fails to parse
    before any runtime guard can see it. Idempotent: an already-defaulted pop is left alone.
    """
    return re.sub(
        r'd\.pop\((["\'])%s\1\)' % re.escape(field),
        lambda m: f'd.pop({m.group(1)}{field}{m.group(1)}, None)',
        source,
    )


def apply_absent_field_tolerance(
    models_dir: Path, couplings: list[tuple[str, str, str]]
) -> list[str]:
    """Make every marker-declared field tolerant of omission in its model's parser."""
    patched: list[str] = []
    for schema_name, field_name, _flag in couplings:
        target = models_dir / f"{_snake(schema_name)}.py"
        if not target.exists():
            raise SystemExit(
                f"hook 0350: {target.name} not found for marker-declared field "
                f"{schema_name}.{field_name}; the parser cannot be made tolerant of an "
                "absent key, so an unleased activation would fail to decode."
            )
        source = target.read_text(encoding="utf-8")
        updated = tolerate_absent_field(source, field_name)
        if updated != source:
            target.write_text(updated, encoding="utf-8")
            patched.append(f"{target.name}:{field_name}")
    return patched


def run(context: dict[str, str]) -> None:
    out_dir = Path(context["out_dir"]).resolve()
    bundled = context.get("bundled_spec_path") or context.get("spec_path")
    if not bundled:
        raise SystemExit("hook 0350: no spec path in context")
    spec = _load_spec(Path(bundled).resolve())
    if not spec:
        raise SystemExit(f"hook 0350: could not load spec at {bundled}")
    schemas = (spec.get("components") or {}).get("schemas") or {}

    couplings = derive_couplings(schemas)
    package_dir = out_dir / "camunda_orchestration_sdk"
    target = package_dir / "runtime" / "present_when_generated.py"
    if not target.parent.exists():
        raise SystemExit(
            f"hook 0350: {target.parent} does not exist — this hook must run after 0300 "
            "(copy_runtime), which creates the runtime package."
        )
    target.write_text(render(couplings), encoding="utf-8")

    patched = apply_absent_field_tolerance(package_dir / "models", couplings)
    print(
        f"hook 0350: wrote {target.name} with {len(couplings)} coupling(s); "
        f"made {len(patched)} field pop(s) absence-tolerant {patched}"
    )
