from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.problem_detail import ProblemDetail
from ...models.tenant_create_request import TenantCreateRequest
from ...models.tenant_create_result import TenantCreateResult
from ...types import Response
def _get_kwargs(body: TenantCreateRequest) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Any | ProblemDetail | TenantCreateResult | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[Any | ProblemDetail | TenantCreateResult]: ...
def sync_detailed(client: AuthenticatedClient | Client, body: TenantCreateRequest) -> Response[Any | ProblemDetail | TenantCreateResult]: ...
def sync(client: AuthenticatedClient | Client, body: TenantCreateRequest, **kwargs: Any) -> TenantCreateResult: ...
async def asyncio_detailed(client: AuthenticatedClient | Client, body: TenantCreateRequest) -> Response[Any | ProblemDetail | TenantCreateResult]: ...
async def asyncio(client: AuthenticatedClient | Client, body: TenantCreateRequest, **kwargs: Any) -> TenantCreateResult: ...
