from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.search_clients_for_tenant_data import SearchClientsForTenantData
from ...models.tenant_client_search_result import TenantClientSearchResult
from ...types import UNSET, Response, Unset
def _get_kwargs(tenant_id: str, body: SearchClientsForTenantData | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> TenantClientSearchResult | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[TenantClientSearchResult]: ...
def sync_detailed(tenant_id: str, client: AuthenticatedClient | Client, body: SearchClientsForTenantData | Unset = UNSET) -> Response[TenantClientSearchResult]: ...
def sync(tenant_id: str, client: AuthenticatedClient | Client, body: SearchClientsForTenantData | Unset = UNSET, **kwargs: Any) -> TenantClientSearchResult: ...
async def asyncio_detailed(tenant_id: str, client: AuthenticatedClient | Client, body: SearchClientsForTenantData | Unset = UNSET) -> Response[TenantClientSearchResult]: ...
async def asyncio(tenant_id: str, client: AuthenticatedClient | Client, body: SearchClientsForTenantData | Unset = UNSET, **kwargs: Any) -> TenantClientSearchResult: ...
