from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.search_clients_for_tenant_data import SearchClientsForTenantData
from ...models.search_clients_for_tenant_response_200 import SearchClientsForTenantResponse200
from ...types import UNSET, Response, Unset
def _get_kwargs(tenant_id: str, body: SearchClientsForTenantData | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> SearchClientsForTenantResponse200 | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[SearchClientsForTenantResponse200]: ...
def sync_detailed(tenant_id: str, client: AuthenticatedClient | Client, body: SearchClientsForTenantData | Unset = UNSET) -> Response[SearchClientsForTenantResponse200]: ...
def sync(tenant_id: str, client: AuthenticatedClient | Client, body: SearchClientsForTenantData | Unset = UNSET, **kwargs: Any) -> SearchClientsForTenantResponse200: ...
async def asyncio_detailed(tenant_id: str, client: AuthenticatedClient | Client, body: SearchClientsForTenantData | Unset = UNSET) -> Response[SearchClientsForTenantResponse200]: ...
async def asyncio(tenant_id: str, client: AuthenticatedClient | Client, body: SearchClientsForTenantData | Unset = UNSET, **kwargs: Any) -> SearchClientsForTenantResponse200: ...
