from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.mapping_rule_search_query_request import MappingRuleSearchQueryRequest
from ...models.search_mapping_rules_for_tenant_response_200 import SearchMappingRulesForTenantResponse200
from ...types import UNSET, Response, Unset
def _get_kwargs(tenant_id: str, body: MappingRuleSearchQueryRequest | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> SearchMappingRulesForTenantResponse200 | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[SearchMappingRulesForTenantResponse200]: ...
def sync_detailed(tenant_id: str, client: AuthenticatedClient | Client, body: MappingRuleSearchQueryRequest | Unset = UNSET) -> Response[SearchMappingRulesForTenantResponse200]: ...
def sync(tenant_id: str, client: AuthenticatedClient | Client, body: MappingRuleSearchQueryRequest | Unset = UNSET, **kwargs: Any) -> SearchMappingRulesForTenantResponse200: ...
async def asyncio_detailed(tenant_id: str, client: AuthenticatedClient | Client, body: MappingRuleSearchQueryRequest | Unset = UNSET) -> Response[SearchMappingRulesForTenantResponse200]: ...
async def asyncio(tenant_id: str, client: AuthenticatedClient | Client, body: MappingRuleSearchQueryRequest | Unset = UNSET, **kwargs: Any) -> SearchMappingRulesForTenantResponse200: ...
