from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.search_users_for_tenant_data import SearchUsersForTenantData
from ...models.search_users_for_tenant_response_200 import SearchUsersForTenantResponse200
from ...types import UNSET, Response, Unset
def _get_kwargs(tenant_id: str, body: SearchUsersForTenantData | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> SearchUsersForTenantResponse200 | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[SearchUsersForTenantResponse200]: ...
def sync_detailed(tenant_id: str, client: AuthenticatedClient | Client, body: SearchUsersForTenantData | Unset = UNSET) -> Response[SearchUsersForTenantResponse200]: ...
def sync(tenant_id: str, client: AuthenticatedClient | Client, body: SearchUsersForTenantData | Unset = UNSET, **kwargs: Any) -> SearchUsersForTenantResponse200: ...
async def asyncio_detailed(tenant_id: str, client: AuthenticatedClient | Client, body: SearchUsersForTenantData | Unset = UNSET) -> Response[SearchUsersForTenantResponse200]: ...
async def asyncio(tenant_id: str, client: AuthenticatedClient | Client, body: SearchUsersForTenantData | Unset = UNSET, **kwargs: Any) -> SearchUsersForTenantResponse200: ...
