from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.role_search_query_request import RoleSearchQueryRequest
from ...models.search_roles_for_tenant_response_200 import SearchRolesForTenantResponse200
from ...types import UNSET, Response, Unset
def _get_kwargs(tenant_id: str, body: RoleSearchQueryRequest | Unset = UNSET) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> SearchRolesForTenantResponse200 | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[SearchRolesForTenantResponse200]: ...
def sync_detailed(tenant_id: str, client: AuthenticatedClient | Client, body: RoleSearchQueryRequest | Unset = UNSET) -> Response[SearchRolesForTenantResponse200]: ...
def sync(tenant_id: str, client: AuthenticatedClient | Client, body: RoleSearchQueryRequest | Unset = UNSET, **kwargs: Any) -> SearchRolesForTenantResponse200: ...
async def asyncio_detailed(tenant_id: str, client: AuthenticatedClient | Client, body: RoleSearchQueryRequest | Unset = UNSET) -> Response[SearchRolesForTenantResponse200]: ...
async def asyncio(tenant_id: str, client: AuthenticatedClient | Client, body: RoleSearchQueryRequest | Unset = UNSET, **kwargs: Any) -> SearchRolesForTenantResponse200: ...
