from typing import Any
import httpx
from ...client import AuthenticatedClient, Client
from ...models.problem_detail import ProblemDetail
from ...models.tenant_update_request import TenantUpdateRequest
from ...models.tenant_update_result import TenantUpdateResult
from ...types import Response
def _get_kwargs(tenant_id: str, body: TenantUpdateRequest) -> dict[str, Any]: ...
def _parse_response(client: AuthenticatedClient | Client, response: httpx.Response) -> ProblemDetail | TenantUpdateResult | None: ...
def _build_response(client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ProblemDetail | TenantUpdateResult]: ...
def sync_detailed(tenant_id: str, client: AuthenticatedClient | Client, body: TenantUpdateRequest) -> Response[ProblemDetail | TenantUpdateResult]: ...
def sync(tenant_id: str, client: AuthenticatedClient | Client, body: TenantUpdateRequest, **kwargs: Any) -> TenantUpdateResult: ...
async def asyncio_detailed(tenant_id: str, client: AuthenticatedClient | Client, body: TenantUpdateRequest) -> Response[ProblemDetail | TenantUpdateResult]: ...
async def asyncio(tenant_id: str, client: AuthenticatedClient | Client, body: TenantUpdateRequest, **kwargs: Any) -> TenantUpdateResult: ...
